package admin

import (
	"os"
	"regexp"
	"sort"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/wow-look-at-my/go-containers/set"
)

// readBundle returns the GENERATED dashboard bundle. It is produced from
// internal/admin/frontend/src by the //go:generate directive in admin.go and is
// gitignored, so a missing file here means the tree was not generated -- the
// same condition that fails the //go:embed at compile time.
func readBundle(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile("static/app.js")
	require.NoError(t, err, "static/app.js is generated by go:generate (scripts/build-admin-frontend.sh)")
	require.Greater(t, len(data), 10_000, "bundle is implausibly small -- did the build emit a stub?")
	return string(data)
}

// The dashboard wires its buttons with inline onclick="App.x(...)" markup, and
// the bundle only exposes App.x for names the TypeScript EXPORTS. A handler that
// is referenced but not exported is a silently dead button -- no build error,
// nothing red in CI, just a control that does nothing when clicked.
//
// This is also the check that would have caught the drift this file was
// rewritten for: the committed bundle had diverged from its TypeScript source,
// and the old assertions (on internal function names) passed against the stale
// artifact while the real source could not have produced a working dashboard.
func TestAdminStaticInlineHandlersAreExported(t *testing.T) {
	body := readBundle(t)

	referenced := map[string]bool{}
	for _, m := range regexp.MustCompile(`App\.([a-zA-Z_][a-zA-Z0-9_]*)`).FindAllStringSubmatch(body, -1) {
		referenced[m[1]] = true
	}
	require.NotEmpty(t, referenced, "no App.* handler references found -- did the markup stop using inline handlers?")

	exportTable := regexp.MustCompile(`(?s)__export\(app_exports, \{(.*?)\}\);`).FindStringSubmatch(body)
	require.Len(t, exportTable, 2, "bundle has no export table: esbuild must run with --global-name=App on a module with exports")

	exported := set.New[string]()
	for _, m := range regexp.MustCompile(`(\w+):\s*\(\)\s*=>`).FindAllStringSubmatch(exportTable[1], -1) {
		exported.Add(m[1])
	}

	var dead []string
	for name := range referenced {
		if !exported.Contains(name) {
			dead = append(dead, name)
		}
	}
	sort.Strings(dead)
	require.Emptyf(t, dead, `inline onclick="App.x(...)" handlers with no matching export (dead buttons): %v`, dead)
}

// The Homebrew snippet must clone the /tap.git endpoint (a bare host 404s) and
// include the Homebrew 6.0+ `brew trust` step, matching llms.txt / README.
func TestAdminStaticHomebrewInstructionsUseTap(t *testing.T) {
	body := readBundle(t)

	require.Contains(t, body, "brew tap pazer/build")
	require.Contains(t, body, "brew install pazer/build/{project}")
	// The \n here are the literal two-char escapes in the bundled string.
	require.Contains(t, body, "/tap.git\\nbrew trust pazer/build\\nbrew install pazer/build/{project}")
}

// Slash-namespaced projects render as a tree on the Projects page. These are the
// class names the rendered markup and the stylesheet agree on, not internal
// function names -- the rendering may be refactored, the markup contract may not.
func TestAdminStaticProjectsRenderAsTree(t *testing.T) {
	body := readBundle(t)

	require.Contains(t, body, "project-folder-row")
	require.Contains(t, body, "project-tree-row")
	require.Contains(t, body, "project-depth-")
}

// The Retention page is reachable: nav entry, route, and the destructive action
// behind it. This page was missing from the TypeScript source entirely while it
// was live in the committed bundle.
func TestAdminStaticHasRetentionPage(t *testing.T) {
	body := readBundle(t)

	require.Contains(t, body, `"#/retention"`)
	require.Contains(t, body, "App.runRetention()")
	require.Contains(t, body, "/api/retention/run")
}

// Private projects mint a signed link per click rather than linking through dl
// (which would 401). Same story: live in the committed bundle, absent from the
// TypeScript source.
func TestAdminStaticPrivateDownloadsMintLinks(t *testing.T) {
	body := readBundle(t)

	require.Contains(t, body, "/download-links")
	require.Contains(t, body, "App.copyTempLink")
	require.Contains(t, body, "App.downloadArtifact")
}

// Every script the dashboard's HTML loads must be a file that actually gets
// embedded. A <script> tag naming a file nothing produces is a 404 and a broken
// page -- which is exactly what a stray html.js tag would be once its helper was
// bundled into app.js.
func TestAdminStaticScriptTagsResolve(t *testing.T) {
	index, err := os.ReadFile("static/index.html")
	require.NoError(t, err)

	srcs := regexp.MustCompile(`<script src="([^"]+)"`).FindAllStringSubmatch(string(index), -1)
	require.NotEmpty(t, srcs)
	for _, m := range srcs {
		_, err := content.ReadFile("static/" + m[1])
		require.NoErrorf(t, err, "index.html loads %q but it is not embedded", m[1])
	}
}

// A site LINK the dashboard hands a user must be the read grammar ("@branch"),
// not the "/branch/" spelling that only redirects. The two are distinguishable
// in the bundle: a link concatenates a runtime branch value onto the path, while
// the endpoint documentation and curl snippets carry the literal "{branch}"
// placeholder -- and those are WRITE routes (PUT/DELETE), where "/branch/" is
// correct and must stay.
func TestAdminStaticSiteLinksUseRefSigil(t *testing.T) {
	body := readBundle(t)

	require.NotContains(t, body, `/branch/" +`,
		`a site link is built by concatenating a branch onto "/branch/"; use siteBranchURL (the "@" form) -- "/branch/" only redirects on reads`)
	require.Contains(t, body, `"/@"`, "the canonical site-link helper is gone")
	// The write endpoints keep the old spelling; if they ever disappear, this
	// test has stopped looking at the thing it thinks it is.
	require.Contains(t, body, "/branch/{branch}", "the site write endpoints should still be documented")
}
