// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^[a-z0-9][a-z0-9._-]{0,127}$`

package api

// validProjectName reports whether input fully matches the regex `^[a-z0-9][a-z0-9._-]{0,127}$`.
func validProjectName(input string) bool {
	state := 0
	chainCount0 := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case c >= '0' && c <= '9':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case c >= '-' && c <= '.':
				if chainCount0 >= 126 {
					state = 128
				} else {
					chainCount0++
				}
			case c >= '0' && c <= '9':
				if chainCount0 >= 126 {
					state = 128
				} else {
					chainCount0++
				}
			case c == '_':
				if chainCount0 >= 126 {
					state = 128
				} else {
					chainCount0++
				}
			case c >= 'a' && c <= 'z':
				if chainCount0 >= 126 {
					state = 128
				} else {
					chainCount0++
				}
			default:
				return false
			}
		case 128:
			switch {
			default:
				return false
			}
		default:
			return false
		}
	}

	switch state {
	case 1, 128:
		return true
	default:
		return false
	}
}
