// Code generated by regex-gen. DO NOT EDIT.
// Source regex: `^[a-z0-9][a-z0-9._-]{0,127}$`

package api

// validProjectName reports whether input fully matches the regex `^[a-z0-9][a-z0-9._-]{0,127}$`.
func validProjectName(input string) bool {
	state := 0
	for i := 0; i < len(input); i++ {
		c := input[i]
		switch state {

		case 0:
			switch {
			case c >= '0' && c <= '9':
				state = 1
			case c >= 'a' && c <= 'z':
				state = 1
			default:
				return false
			}
		case 1:
			switch {
			case c >= '-' && c <= '.':
				state = 2
			case c >= '0' && c <= '9':
				state = 2
			case c == '_':
				state = 2
			case c >= 'a' && c <= 'z':
				state = 2
			default:
				return false
			}
		case 2:
			switch {
			case c >= '-' && c <= '.':
				state = 3
			case c >= '0' && c <= '9':
				state = 3
			case c == '_':
				state = 3
			case c >= 'a' && c <= 'z':
				state = 3
			default:
				return false
			}
		case 3:
			switch {
			case c >= '-' && c <= '.':
				state = 4
			case c >= '0' && c <= '9':
				state = 4
			case c == '_':
				state = 4
			case c >= 'a' && c <= 'z':
				state = 4
			default:
				return false
			}
		case 4:
			switch {
			case c >= '-' && c <= '.':
				state = 5
			case c >= '0' && c <= '9':
				state = 5
			case c == '_':
				state = 5
			case c >= 'a' && c <= 'z':
				state = 5
			default:
				return false
			}
		case 5:
			switch {
			case c >= '-' && c <= '.':
				state = 6
			case c >= '0' && c <= '9':
				state = 6
			case c == '_':
				state = 6
			case c >= 'a' && c <= 'z':
				state = 6
			default:
				return false
			}
		case 6:
			switch {
			case c >= '-' && c <= '.':
				state = 7
			case c >= '0' && c <= '9':
				state = 7
			case c == '_':
				state = 7
			case c >= 'a' && c <= 'z':
				state = 7
			default:
				return false
			}
		case 7:
			switch {
			case c >= '-' && c <= '.':
				state = 8
			case c >= '0' && c <= '9':
				state = 8
			case c == '_':
				state = 8
			case c >= 'a' && c <= 'z':
				state = 8
			default:
				return false
			}
		case 8:
			switch {
			case c >= '-' && c <= '.':
				state = 9
			case c >= '0' && c <= '9':
				state = 9
			case c == '_':
				state = 9
			case c >= 'a' && c <= 'z':
				state = 9
			default:
				return false
			}
		case 9:
			switch {
			case c >= '-' && c <= '.':
				state = 10
			case c >= '0' && c <= '9':
				state = 10
			case c == '_':
				state = 10
			case c >= 'a' && c <= 'z':
				state = 10
			default:
				return false
			}
		case 10:
			switch {
			case c >= '-' && c <= '.':
				state = 11
			case c >= '0' && c <= '9':
				state = 11
			case c == '_':
				state = 11
			case c >= 'a' && c <= 'z':
				state = 11
			default:
				return false
			}
		case 11:
			switch {
			case c >= '-' && c <= '.':
				state = 12
			case c >= '0' && c <= '9':
				state = 12
			case c == '_':
				state = 12
			case c >= 'a' && c <= 'z':
				state = 12
			default:
				return false
			}
		case 12:
			switch {
			case c >= '-' && c <= '.':
				state = 13
			case c >= '0' && c <= '9':
				state = 13
			case c == '_':
				state = 13
			case c >= 'a' && c <= 'z':
				state = 13
			default:
				return false
			}
		case 13:
			switch {
			case c >= '-' && c <= '.':
				state = 14
			case c >= '0' && c <= '9':
				state = 14
			case c == '_':
				state = 14
			case c >= 'a' && c <= 'z':
				state = 14
			default:
				return false
			}
		case 14:
			switch {
			case c >= '-' && c <= '.':
				state = 15
			case c >= '0' && c <= '9':
				state = 15
			case c == '_':
				state = 15
			case c >= 'a' && c <= 'z':
				state = 15
			default:
				return false
			}
		case 15:
			switch {
			case c >= '-' && c <= '.':
				state = 16
			case c >= '0' && c <= '9':
				state = 16
			case c == '_':
				state = 16
			case c >= 'a' && c <= 'z':
				state = 16
			default:
				return false
			}
		case 16:
			switch {
			case c >= '-' && c <= '.':
				state = 17
			case c >= '0' && c <= '9':
				state = 17
			case c == '_':
				state = 17
			case c >= 'a' && c <= 'z':
				state = 17
			default:
				return false
			}
		case 17:
			switch {
			case c >= '-' && c <= '.':
				state = 18
			case c >= '0' && c <= '9':
				state = 18
			case c == '_':
				state = 18
			case c >= 'a' && c <= 'z':
				state = 18
			default:
				return false
			}
		case 18:
			switch {
			case c >= '-' && c <= '.':
				state = 19
			case c >= '0' && c <= '9':
				state = 19
			case c == '_':
				state = 19
			case c >= 'a' && c <= 'z':
				state = 19
			default:
				return false
			}
		case 19:
			switch {
			case c >= '-' && c <= '.':
				state = 20
			case c >= '0' && c <= '9':
				state = 20
			case c == '_':
				state = 20
			case c >= 'a' && c <= 'z':
				state = 20
			default:
				return false
			}
		case 20:
			switch {
			case c >= '-' && c <= '.':
				state = 21
			case c >= '0' && c <= '9':
				state = 21
			case c == '_':
				state = 21
			case c >= 'a' && c <= 'z':
				state = 21
			default:
				return false
			}
		case 21:
			switch {
			case c >= '-' && c <= '.':
				state = 22
			case c >= '0' && c <= '9':
				state = 22
			case c == '_':
				state = 22
			case c >= 'a' && c <= 'z':
				state = 22
			default:
				return false
			}
		case 22:
			switch {
			case c >= '-' && c <= '.':
				state = 23
			case c >= '0' && c <= '9':
				state = 23
			case c == '_':
				state = 23
			case c >= 'a' && c <= 'z':
				state = 23
			default:
				return false
			}
		case 23:
			switch {
			case c >= '-' && c <= '.':
				state = 24
			case c >= '0' && c <= '9':
				state = 24
			case c == '_':
				state = 24
			case c >= 'a' && c <= 'z':
				state = 24
			default:
				return false
			}
		case 24:
			switch {
			case c >= '-' && c <= '.':
				state = 25
			case c >= '0' && c <= '9':
				state = 25
			case c == '_':
				state = 25
			case c >= 'a' && c <= 'z':
				state = 25
			default:
				return false
			}
		case 25:
			switch {
			case c >= '-' && c <= '.':
				state = 26
			case c >= '0' && c <= '9':
				state = 26
			case c == '_':
				state = 26
			case c >= 'a' && c <= 'z':
				state = 26
			default:
				return false
			}
		case 26:
			switch {
			case c >= '-' && c <= '.':
				state = 27
			case c >= '0' && c <= '9':
				state = 27
			case c == '_':
				state = 27
			case c >= 'a' && c <= 'z':
				state = 27
			default:
				return false
			}
		case 27:
			switch {
			case c >= '-' && c <= '.':
				state = 28
			case c >= '0' && c <= '9':
				state = 28
			case c == '_':
				state = 28
			case c >= 'a' && c <= 'z':
				state = 28
			default:
				return false
			}
		case 28:
			switch {
			case c >= '-' && c <= '.':
				state = 29
			case c >= '0' && c <= '9':
				state = 29
			case c == '_':
				state = 29
			case c >= 'a' && c <= 'z':
				state = 29
			default:
				return false
			}
		case 29:
			switch {
			case c >= '-' && c <= '.':
				state = 30
			case c >= '0' && c <= '9':
				state = 30
			case c == '_':
				state = 30
			case c >= 'a' && c <= 'z':
				state = 30
			default:
				return false
			}
		case 30:
			switch {
			case c >= '-' && c <= '.':
				state = 31
			case c >= '0' && c <= '9':
				state = 31
			case c == '_':
				state = 31
			case c >= 'a' && c <= 'z':
				state = 31
			default:
				return false
			}
		case 31:
			switch {
			case c >= '-' && c <= '.':
				state = 32
			case c >= '0' && c <= '9':
				state = 32
			case c == '_':
				state = 32
			case c >= 'a' && c <= 'z':
				state = 32
			default:
				return false
			}
		case 32:
			switch {
			case c >= '-' && c <= '.':
				state = 33
			case c >= '0' && c <= '9':
				state = 33
			case c == '_':
				state = 33
			case c >= 'a' && c <= 'z':
				state = 33
			default:
				return false
			}
		case 33:
			switch {
			case c >= '-' && c <= '.':
				state = 34
			case c >= '0' && c <= '9':
				state = 34
			case c == '_':
				state = 34
			case c >= 'a' && c <= 'z':
				state = 34
			default:
				return false
			}
		case 34:
			switch {
			case c >= '-' && c <= '.':
				state = 35
			case c >= '0' && c <= '9':
				state = 35
			case c == '_':
				state = 35
			case c >= 'a' && c <= 'z':
				state = 35
			default:
				return false
			}
		case 35:
			switch {
			case c >= '-' && c <= '.':
				state = 36
			case c >= '0' && c <= '9':
				state = 36
			case c == '_':
				state = 36
			case c >= 'a' && c <= 'z':
				state = 36
			default:
				return false
			}
		case 36:
			switch {
			case c >= '-' && c <= '.':
				state = 37
			case c >= '0' && c <= '9':
				state = 37
			case c == '_':
				state = 37
			case c >= 'a' && c <= 'z':
				state = 37
			default:
				return false
			}
		case 37:
			switch {
			case c >= '-' && c <= '.':
				state = 38
			case c >= '0' && c <= '9':
				state = 38
			case c == '_':
				state = 38
			case c >= 'a' && c <= 'z':
				state = 38
			default:
				return false
			}
		case 38:
			switch {
			case c >= '-' && c <= '.':
				state = 39
			case c >= '0' && c <= '9':
				state = 39
			case c == '_':
				state = 39
			case c >= 'a' && c <= 'z':
				state = 39
			default:
				return false
			}
		case 39:
			switch {
			case c >= '-' && c <= '.':
				state = 40
			case c >= '0' && c <= '9':
				state = 40
			case c == '_':
				state = 40
			case c >= 'a' && c <= 'z':
				state = 40
			default:
				return false
			}
		case 40:
			switch {
			case c >= '-' && c <= '.':
				state = 41
			case c >= '0' && c <= '9':
				state = 41
			case c == '_':
				state = 41
			case c >= 'a' && c <= 'z':
				state = 41
			default:
				return false
			}
		case 41:
			switch {
			case c >= '-' && c <= '.':
				state = 42
			case c >= '0' && c <= '9':
				state = 42
			case c == '_':
				state = 42
			case c >= 'a' && c <= 'z':
				state = 42
			default:
				return false
			}
		case 42:
			switch {
			case c >= '-' && c <= '.':
				state = 43
			case c >= '0' && c <= '9':
				state = 43
			case c == '_':
				state = 43
			case c >= 'a' && c <= 'z':
				state = 43
			default:
				return false
			}
		case 43:
			switch {
			case c >= '-' && c <= '.':
				state = 44
			case c >= '0' && c <= '9':
				state = 44
			case c == '_':
				state = 44
			case c >= 'a' && c <= 'z':
				state = 44
			default:
				return false
			}
		case 44:
			switch {
			case c >= '-' && c <= '.':
				state = 45
			case c >= '0' && c <= '9':
				state = 45
			case c == '_':
				state = 45
			case c >= 'a' && c <= 'z':
				state = 45
			default:
				return false
			}
		case 45:
			switch {
			case c >= '-' && c <= '.':
				state = 46
			case c >= '0' && c <= '9':
				state = 46
			case c == '_':
				state = 46
			case c >= 'a' && c <= 'z':
				state = 46
			default:
				return false
			}
		case 46:
			switch {
			case c >= '-' && c <= '.':
				state = 47
			case c >= '0' && c <= '9':
				state = 47
			case c == '_':
				state = 47
			case c >= 'a' && c <= 'z':
				state = 47
			default:
				return false
			}
		case 47:
			switch {
			case c >= '-' && c <= '.':
				state = 48
			case c >= '0' && c <= '9':
				state = 48
			case c == '_':
				state = 48
			case c >= 'a' && c <= 'z':
				state = 48
			default:
				return false
			}
		case 48:
			switch {
			case c >= '-' && c <= '.':
				state = 49
			case c >= '0' && c <= '9':
				state = 49
			case c == '_':
				state = 49
			case c >= 'a' && c <= 'z':
				state = 49
			default:
				return false
			}
		case 49:
			switch {
			case c >= '-' && c <= '.':
				state = 50
			case c >= '0' && c <= '9':
				state = 50
			case c == '_':
				state = 50
			case c >= 'a' && c <= 'z':
				state = 50
			default:
				return false
			}
		case 50:
			switch {
			case c >= '-' && c <= '.':
				state = 51
			case c >= '0' && c <= '9':
				state = 51
			case c == '_':
				state = 51
			case c >= 'a' && c <= 'z':
				state = 51
			default:
				return false
			}
		case 51:
			switch {
			case c >= '-' && c <= '.':
				state = 52
			case c >= '0' && c <= '9':
				state = 52
			case c == '_':
				state = 52
			case c >= 'a' && c <= 'z':
				state = 52
			default:
				return false
			}
		case 52:
			switch {
			case c >= '-' && c <= '.':
				state = 53
			case c >= '0' && c <= '9':
				state = 53
			case c == '_':
				state = 53
			case c >= 'a' && c <= 'z':
				state = 53
			default:
				return false
			}
		case 53:
			switch {
			case c >= '-' && c <= '.':
				state = 54
			case c >= '0' && c <= '9':
				state = 54
			case c == '_':
				state = 54
			case c >= 'a' && c <= 'z':
				state = 54
			default:
				return false
			}
		case 54:
			switch {
			case c >= '-' && c <= '.':
				state = 55
			case c >= '0' && c <= '9':
				state = 55
			case c == '_':
				state = 55
			case c >= 'a' && c <= 'z':
				state = 55
			default:
				return false
			}
		case 55:
			switch {
			case c >= '-' && c <= '.':
				state = 56
			case c >= '0' && c <= '9':
				state = 56
			case c == '_':
				state = 56
			case c >= 'a' && c <= 'z':
				state = 56
			default:
				return false
			}
		case 56:
			switch {
			case c >= '-' && c <= '.':
				state = 57
			case c >= '0' && c <= '9':
				state = 57
			case c == '_':
				state = 57
			case c >= 'a' && c <= 'z':
				state = 57
			default:
				return false
			}
		case 57:
			switch {
			case c >= '-' && c <= '.':
				state = 58
			case c >= '0' && c <= '9':
				state = 58
			case c == '_':
				state = 58
			case c >= 'a' && c <= 'z':
				state = 58
			default:
				return false
			}
		case 58:
			switch {
			case c >= '-' && c <= '.':
				state = 59
			case c >= '0' && c <= '9':
				state = 59
			case c == '_':
				state = 59
			case c >= 'a' && c <= 'z':
				state = 59
			default:
				return false
			}
		case 59:
			switch {
			case c >= '-' && c <= '.':
				state = 60
			case c >= '0' && c <= '9':
				state = 60
			case c == '_':
				state = 60
			case c >= 'a' && c <= 'z':
				state = 60
			default:
				return false
			}
		case 60:
			switch {
			case c >= '-' && c <= '.':
				state = 61
			case c >= '0' && c <= '9':
				state = 61
			case c == '_':
				state = 61
			case c >= 'a' && c <= 'z':
				state = 61
			default:
				return false
			}
		case 61:
			switch {
			case c >= '-' && c <= '.':
				state = 62
			case c >= '0' && c <= '9':
				state = 62
			case c == '_':
				state = 62
			case c >= 'a' && c <= 'z':
				state = 62
			default:
				return false
			}
		case 62:
			switch {
			case c >= '-' && c <= '.':
				state = 63
			case c >= '0' && c <= '9':
				state = 63
			case c == '_':
				state = 63
			case c >= 'a' && c <= 'z':
				state = 63
			default:
				return false
			}
		case 63:
			switch {
			case c >= '-' && c <= '.':
				state = 64
			case c >= '0' && c <= '9':
				state = 64
			case c == '_':
				state = 64
			case c >= 'a' && c <= 'z':
				state = 64
			default:
				return false
			}
		case 64:
			switch {
			case c >= '-' && c <= '.':
				state = 65
			case c >= '0' && c <= '9':
				state = 65
			case c == '_':
				state = 65
			case c >= 'a' && c <= 'z':
				state = 65
			default:
				return false
			}
		case 65:
			switch {
			case c >= '-' && c <= '.':
				state = 66
			case c >= '0' && c <= '9':
				state = 66
			case c == '_':
				state = 66
			case c >= 'a' && c <= 'z':
				state = 66
			default:
				return false
			}
		case 66:
			switch {
			case c >= '-' && c <= '.':
				state = 67
			case c >= '0' && c <= '9':
				state = 67
			case c == '_':
				state = 67
			case c >= 'a' && c <= 'z':
				state = 67
			default:
				return false
			}
		case 67:
			switch {
			case c >= '-' && c <= '.':
				state = 68
			case c >= '0' && c <= '9':
				state = 68
			case c == '_':
				state = 68
			case c >= 'a' && c <= 'z':
				state = 68
			default:
				return false
			}
		case 68:
			switch {
			case c >= '-' && c <= '.':
				state = 69
			case c >= '0' && c <= '9':
				state = 69
			case c == '_':
				state = 69
			case c >= 'a' && c <= 'z':
				state = 69
			default:
				return false
			}
		case 69:
			switch {
			case c >= '-' && c <= '.':
				state = 70
			case c >= '0' && c <= '9':
				state = 70
			case c == '_':
				state = 70
			case c >= 'a' && c <= 'z':
				state = 70
			default:
				return false
			}
		case 70:
			switch {
			case c >= '-' && c <= '.':
				state = 71
			case c >= '0' && c <= '9':
				state = 71
			case c == '_':
				state = 71
			case c >= 'a' && c <= 'z':
				state = 71
			default:
				return false
			}
		case 71:
			switch {
			case c >= '-' && c <= '.':
				state = 72
			case c >= '0' && c <= '9':
				state = 72
			case c == '_':
				state = 72
			case c >= 'a' && c <= 'z':
				state = 72
			default:
				return false
			}
		case 72:
			switch {
			case c >= '-' && c <= '.':
				state = 73
			case c >= '0' && c <= '9':
				state = 73
			case c == '_':
				state = 73
			case c >= 'a' && c <= 'z':
				state = 73
			default:
				return false
			}
		case 73:
			switch {
			case c >= '-' && c <= '.':
				state = 74
			case c >= '0' && c <= '9':
				state = 74
			case c == '_':
				state = 74
			case c >= 'a' && c <= 'z':
				state = 74
			default:
				return false
			}
		case 74:
			switch {
			case c >= '-' && c <= '.':
				state = 75
			case c >= '0' && c <= '9':
				state = 75
			case c == '_':
				state = 75
			case c >= 'a' && c <= 'z':
				state = 75
			default:
				return false
			}
		case 75:
			switch {
			case c >= '-' && c <= '.':
				state = 76
			case c >= '0' && c <= '9':
				state = 76
			case c == '_':
				state = 76
			case c >= 'a' && c <= 'z':
				state = 76
			default:
				return false
			}
		case 76:
			switch {
			case c >= '-' && c <= '.':
				state = 77
			case c >= '0' && c <= '9':
				state = 77
			case c == '_':
				state = 77
			case c >= 'a' && c <= 'z':
				state = 77
			default:
				return false
			}
		case 77:
			switch {
			case c >= '-' && c <= '.':
				state = 78
			case c >= '0' && c <= '9':
				state = 78
			case c == '_':
				state = 78
			case c >= 'a' && c <= 'z':
				state = 78
			default:
				return false
			}
		case 78:
			switch {
			case c >= '-' && c <= '.':
				state = 79
			case c >= '0' && c <= '9':
				state = 79
			case c == '_':
				state = 79
			case c >= 'a' && c <= 'z':
				state = 79
			default:
				return false
			}
		case 79:
			switch {
			case c >= '-' && c <= '.':
				state = 80
			case c >= '0' && c <= '9':
				state = 80
			case c == '_':
				state = 80
			case c >= 'a' && c <= 'z':
				state = 80
			default:
				return false
			}
		case 80:
			switch {
			case c >= '-' && c <= '.':
				state = 81
			case c >= '0' && c <= '9':
				state = 81
			case c == '_':
				state = 81
			case c >= 'a' && c <= 'z':
				state = 81
			default:
				return false
			}
		case 81:
			switch {
			case c >= '-' && c <= '.':
				state = 82
			case c >= '0' && c <= '9':
				state = 82
			case c == '_':
				state = 82
			case c >= 'a' && c <= 'z':
				state = 82
			default:
				return false
			}
		case 82:
			switch {
			case c >= '-' && c <= '.':
				state = 83
			case c >= '0' && c <= '9':
				state = 83
			case c == '_':
				state = 83
			case c >= 'a' && c <= 'z':
				state = 83
			default:
				return false
			}
		case 83:
			switch {
			case c >= '-' && c <= '.':
				state = 84
			case c >= '0' && c <= '9':
				state = 84
			case c == '_':
				state = 84
			case c >= 'a' && c <= 'z':
				state = 84
			default:
				return false
			}
		case 84:
			switch {
			case c >= '-' && c <= '.':
				state = 85
			case c >= '0' && c <= '9':
				state = 85
			case c == '_':
				state = 85
			case c >= 'a' && c <= 'z':
				state = 85
			default:
				return false
			}
		case 85:
			switch {
			case c >= '-' && c <= '.':
				state = 86
			case c >= '0' && c <= '9':
				state = 86
			case c == '_':
				state = 86
			case c >= 'a' && c <= 'z':
				state = 86
			default:
				return false
			}
		case 86:
			switch {
			case c >= '-' && c <= '.':
				state = 87
			case c >= '0' && c <= '9':
				state = 87
			case c == '_':
				state = 87
			case c >= 'a' && c <= 'z':
				state = 87
			default:
				return false
			}
		case 87:
			switch {
			case c >= '-' && c <= '.':
				state = 88
			case c >= '0' && c <= '9':
				state = 88
			case c == '_':
				state = 88
			case c >= 'a' && c <= 'z':
				state = 88
			default:
				return false
			}
		case 88:
			switch {
			case c >= '-' && c <= '.':
				state = 89
			case c >= '0' && c <= '9':
				state = 89
			case c == '_':
				state = 89
			case c >= 'a' && c <= 'z':
				state = 89
			default:
				return false
			}
		case 89:
			switch {
			case c >= '-' && c <= '.':
				state = 90
			case c >= '0' && c <= '9':
				state = 90
			case c == '_':
				state = 90
			case c >= 'a' && c <= 'z':
				state = 90
			default:
				return false
			}
		case 90:
			switch {
			case c >= '-' && c <= '.':
				state = 91
			case c >= '0' && c <= '9':
				state = 91
			case c == '_':
				state = 91
			case c >= 'a' && c <= 'z':
				state = 91
			default:
				return false
			}
		case 91:
			switch {
			case c >= '-' && c <= '.':
				state = 92
			case c >= '0' && c <= '9':
				state = 92
			case c == '_':
				state = 92
			case c >= 'a' && c <= 'z':
				state = 92
			default:
				return false
			}
		case 92:
			switch {
			case c >= '-' && c <= '.':
				state = 93
			case c >= '0' && c <= '9':
				state = 93
			case c == '_':
				state = 93
			case c >= 'a' && c <= 'z':
				state = 93
			default:
				return false
			}
		case 93:
			switch {
			case c >= '-' && c <= '.':
				state = 94
			case c >= '0' && c <= '9':
				state = 94
			case c == '_':
				state = 94
			case c >= 'a' && c <= 'z':
				state = 94
			default:
				return false
			}
		case 94:
			switch {
			case c >= '-' && c <= '.':
				state = 95
			case c >= '0' && c <= '9':
				state = 95
			case c == '_':
				state = 95
			case c >= 'a' && c <= 'z':
				state = 95
			default:
				return false
			}
		case 95:
			switch {
			case c >= '-' && c <= '.':
				state = 96
			case c >= '0' && c <= '9':
				state = 96
			case c == '_':
				state = 96
			case c >= 'a' && c <= 'z':
				state = 96
			default:
				return false
			}
		case 96:
			switch {
			case c >= '-' && c <= '.':
				state = 97
			case c >= '0' && c <= '9':
				state = 97
			case c == '_':
				state = 97
			case c >= 'a' && c <= 'z':
				state = 97
			default:
				return false
			}
		case 97:
			switch {
			case c >= '-' && c <= '.':
				state = 98
			case c >= '0' && c <= '9':
				state = 98
			case c == '_':
				state = 98
			case c >= 'a' && c <= 'z':
				state = 98
			default:
				return false
			}
		case 98:
			switch {
			case c >= '-' && c <= '.':
				state = 99
			case c >= '0' && c <= '9':
				state = 99
			case c == '_':
				state = 99
			case c >= 'a' && c <= 'z':
				state = 99
			default:
				return false
			}
		case 99:
			switch {
			case c >= '-' && c <= '.':
				state = 100
			case c >= '0' && c <= '9':
				state = 100
			case c == '_':
				state = 100
			case c >= 'a' && c <= 'z':
				state = 100
			default:
				return false
			}
		case 100:
			switch {
			case c >= '-' && c <= '.':
				state = 101
			case c >= '0' && c <= '9':
				state = 101
			case c == '_':
				state = 101
			case c >= 'a' && c <= 'z':
				state = 101
			default:
				return false
			}
		case 101:
			switch {
			case c >= '-' && c <= '.':
				state = 102
			case c >= '0' && c <= '9':
				state = 102
			case c == '_':
				state = 102
			case c >= 'a' && c <= 'z':
				state = 102
			default:
				return false
			}
		case 102:
			switch {
			case c >= '-' && c <= '.':
				state = 103
			case c >= '0' && c <= '9':
				state = 103
			case c == '_':
				state = 103
			case c >= 'a' && c <= 'z':
				state = 103
			default:
				return false
			}
		case 103:
			switch {
			case c >= '-' && c <= '.':
				state = 104
			case c >= '0' && c <= '9':
				state = 104
			case c == '_':
				state = 104
			case c >= 'a' && c <= 'z':
				state = 104
			default:
				return false
			}
		case 104:
			switch {
			case c >= '-' && c <= '.':
				state = 105
			case c >= '0' && c <= '9':
				state = 105
			case c == '_':
				state = 105
			case c >= 'a' && c <= 'z':
				state = 105
			default:
				return false
			}
		case 105:
			switch {
			case c >= '-' && c <= '.':
				state = 106
			case c >= '0' && c <= '9':
				state = 106
			case c == '_':
				state = 106
			case c >= 'a' && c <= 'z':
				state = 106
			default:
				return false
			}
		case 106:
			switch {
			case c >= '-' && c <= '.':
				state = 107
			case c >= '0' && c <= '9':
				state = 107
			case c == '_':
				state = 107
			case c >= 'a' && c <= 'z':
				state = 107
			default:
				return false
			}
		case 107:
			switch {
			case c >= '-' && c <= '.':
				state = 108
			case c >= '0' && c <= '9':
				state = 108
			case c == '_':
				state = 108
			case c >= 'a' && c <= 'z':
				state = 108
			default:
				return false
			}
		case 108:
			switch {
			case c >= '-' && c <= '.':
				state = 109
			case c >= '0' && c <= '9':
				state = 109
			case c == '_':
				state = 109
			case c >= 'a' && c <= 'z':
				state = 109
			default:
				return false
			}
		case 109:
			switch {
			case c >= '-' && c <= '.':
				state = 110
			case c >= '0' && c <= '9':
				state = 110
			case c == '_':
				state = 110
			case c >= 'a' && c <= 'z':
				state = 110
			default:
				return false
			}
		case 110:
			switch {
			case c >= '-' && c <= '.':
				state = 111
			case c >= '0' && c <= '9':
				state = 111
			case c == '_':
				state = 111
			case c >= 'a' && c <= 'z':
				state = 111
			default:
				return false
			}
		case 111:
			switch {
			case c >= '-' && c <= '.':
				state = 112
			case c >= '0' && c <= '9':
				state = 112
			case c == '_':
				state = 112
			case c >= 'a' && c <= 'z':
				state = 112
			default:
				return false
			}
		case 112:
			switch {
			case c >= '-' && c <= '.':
				state = 113
			case c >= '0' && c <= '9':
				state = 113
			case c == '_':
				state = 113
			case c >= 'a' && c <= 'z':
				state = 113
			default:
				return false
			}
		case 113:
			switch {
			case c >= '-' && c <= '.':
				state = 114
			case c >= '0' && c <= '9':
				state = 114
			case c == '_':
				state = 114
			case c >= 'a' && c <= 'z':
				state = 114
			default:
				return false
			}
		case 114:
			switch {
			case c >= '-' && c <= '.':
				state = 115
			case c >= '0' && c <= '9':
				state = 115
			case c == '_':
				state = 115
			case c >= 'a' && c <= 'z':
				state = 115
			default:
				return false
			}
		case 115:
			switch {
			case c >= '-' && c <= '.':
				state = 116
			case c >= '0' && c <= '9':
				state = 116
			case c == '_':
				state = 116
			case c >= 'a' && c <= 'z':
				state = 116
			default:
				return false
			}
		case 116:
			switch {
			case c >= '-' && c <= '.':
				state = 117
			case c >= '0' && c <= '9':
				state = 117
			case c == '_':
				state = 117
			case c >= 'a' && c <= 'z':
				state = 117
			default:
				return false
			}
		case 117:
			switch {
			case c >= '-' && c <= '.':
				state = 118
			case c >= '0' && c <= '9':
				state = 118
			case c == '_':
				state = 118
			case c >= 'a' && c <= 'z':
				state = 118
			default:
				return false
			}
		case 118:
			switch {
			case c >= '-' && c <= '.':
				state = 119
			case c >= '0' && c <= '9':
				state = 119
			case c == '_':
				state = 119
			case c >= 'a' && c <= 'z':
				state = 119
			default:
				return false
			}
		case 119:
			switch {
			case c >= '-' && c <= '.':
				state = 120
			case c >= '0' && c <= '9':
				state = 120
			case c == '_':
				state = 120
			case c >= 'a' && c <= 'z':
				state = 120
			default:
				return false
			}
		case 120:
			switch {
			case c >= '-' && c <= '.':
				state = 121
			case c >= '0' && c <= '9':
				state = 121
			case c == '_':
				state = 121
			case c >= 'a' && c <= 'z':
				state = 121
			default:
				return false
			}
		case 121:
			switch {
			case c >= '-' && c <= '.':
				state = 122
			case c >= '0' && c <= '9':
				state = 122
			case c == '_':
				state = 122
			case c >= 'a' && c <= 'z':
				state = 122
			default:
				return false
			}
		case 122:
			switch {
			case c >= '-' && c <= '.':
				state = 123
			case c >= '0' && c <= '9':
				state = 123
			case c == '_':
				state = 123
			case c >= 'a' && c <= 'z':
				state = 123
			default:
				return false
			}
		case 123:
			switch {
			case c >= '-' && c <= '.':
				state = 124
			case c >= '0' && c <= '9':
				state = 124
			case c == '_':
				state = 124
			case c >= 'a' && c <= 'z':
				state = 124
			default:
				return false
			}
		case 124:
			switch {
			case c >= '-' && c <= '.':
				state = 125
			case c >= '0' && c <= '9':
				state = 125
			case c == '_':
				state = 125
			case c >= 'a' && c <= 'z':
				state = 125
			default:
				return false
			}
		case 125:
			switch {
			case c >= '-' && c <= '.':
				state = 126
			case c >= '0' && c <= '9':
				state = 126
			case c == '_':
				state = 126
			case c >= 'a' && c <= 'z':
				state = 126
			default:
				return false
			}
		case 126:
			switch {
			case c >= '-' && c <= '.':
				state = 127
			case c >= '0' && c <= '9':
				state = 127
			case c == '_':
				state = 127
			case c >= 'a' && c <= 'z':
				state = 127
			default:
				return false
			}
		case 127:
			switch {
			case c >= '-' && c <= '.':
				state = 128
			case c >= '0' && c <= '9':
				state = 128
			case c == '_':
				state = 128
			case c >= 'a' && c <= 'z':
				state = 128
			default:
				return false
			}
		case 128:
			switch {
			default:
				return false
			}
		default:
			return false
		}
	}

	switch state {
	case 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128:
		return true
	default:
		return false
	}
}
