// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: admin.sql

package dbgen

import (
	"context"
	"time"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM projects) AS project_count,
    (SELECT COUNT(*) FROM releases) AS release_count,
    (SELECT COUNT(*) FROM artifacts) AS artifact_count,
    CAST((SELECT COALESCE(SUM(size), 0) FROM artifacts) AS INTEGER) AS total_storage_bytes,
    (SELECT COUNT(*) FROM api_tokens) AS token_count,
    (SELECT COUNT(*) FROM oidc_policies) AS oidc_policy_count
`

type GetDashboardStatsRow struct {
	ProjectCount      int64
	ReleaseCount      int64
	ArtifactCount     int64
	TotalStorageBytes int64
	TokenCount        int64
	OidcPolicyCount   int64
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.ProjectCount,
		&i.ReleaseCount,
		&i.ArtifactCount,
		&i.TotalStorageBytes,
		&i.TokenCount,
		&i.OidcPolicyCount,
	)
	return i, err
}

const listOIDCPolicyDetails = `-- name: ListOIDCPolicyDetails :many
SELECT o.id, o.issuer, o.subject_pattern, o.audience, o.project_id, o.scopes, o.created_at,
       COALESCE(p.name, '') AS project_name
FROM oidc_policies o
LEFT JOIN projects p ON o.project_id = p.id
ORDER BY o.created_at DESC
`

type ListOIDCPolicyDetailsRow struct {
	ID             int64
	Issuer         string
	SubjectPattern string
	Audience       string
	ProjectID      *int64
	Scopes         string
	CreatedAt      time.Time
	ProjectName    string
}

func (q *Queries) ListOIDCPolicyDetails(ctx context.Context) ([]ListOIDCPolicyDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOIDCPolicyDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOIDCPolicyDetailsRow{}
	for rows.Next() {
		var i ListOIDCPolicyDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.SubjectPattern,
			&i.Audience,
			&i.ProjectID,
			&i.Scopes,
			&i.CreatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectSummaries = `-- name: ListProjectSummaries :many
SELECT p.id, p.name, p.description, p.homepage, p.license, p.is_private, p.versioning,
       p.created_at, p.updated_at,
       (SELECT COUNT(*) FROM releases WHERE project_id = p.id) AS release_count,
       (SELECT COUNT(*) FROM artifacts a JOIN releases r ON a.release_id = r.id WHERE r.project_id = p.id) AS artifact_count
FROM projects p
ORDER BY p.name
`

type ListProjectSummariesRow struct {
	ID            int64
	Name          string
	Description   string
	Homepage      string
	License       string
	IsPrivate     bool
	Versioning    string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ReleaseCount  int64
	ArtifactCount int64
}

func (q *Queries) ListProjectSummaries(ctx context.Context) ([]ListProjectSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectSummariesRow{}
	for rows.Next() {
		var i ListProjectSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Homepage,
			&i.License,
			&i.IsPrivate,
			&i.Versioning,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseCount,
			&i.ArtifactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentReleases = `-- name: ListRecentReleases :many
SELECT r.id, r.project_id, r.version, r.version_num, r.git_branch, r.git_commit,
       r.notes, r.published, r.created_at, r.published_at, p.name AS project_name
FROM releases r
JOIN projects p ON r.project_id = p.id
ORDER BY r.created_at DESC, r.id DESC
LIMIT ?
`

type ListRecentReleasesRow struct {
	ID          int64
	ProjectID   int64
	Version     string
	VersionNum  int64
	GitBranch   string
	GitCommit   string
	Notes       string
	Published   bool
	CreatedAt   time.Time
	PublishedAt *time.Time
	ProjectName string
}

func (q *Queries) ListRecentReleases(ctx context.Context, limit int64) ([]ListRecentReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentReleases, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentReleasesRow{}
	for rows.Next() {
		var i ListRecentReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.VersionNum,
			&i.GitBranch,
			&i.GitCommit,
			&i.Notes,
			&i.Published,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseSummaries = `-- name: ListReleaseSummaries :many
SELECT r.id, r.project_id, r.version, r.version_num, r.git_branch, r.git_commit,
       r.notes, r.published, r.created_at, r.published_at,
       (SELECT COUNT(*) FROM artifacts WHERE release_id = r.id) AS artifact_count
FROM releases r
WHERE r.project_id = ?
ORDER BY r.version_num DESC
`

type ListReleaseSummariesRow struct {
	ID            int64
	ProjectID     int64
	Version       string
	VersionNum    int64
	GitBranch     string
	GitCommit     string
	Notes         string
	Published     bool
	CreatedAt     time.Time
	PublishedAt   *time.Time
	ArtifactCount int64
}

func (q *Queries) ListReleaseSummaries(ctx context.Context, projectID int64) ([]ListReleaseSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseSummaries, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseSummariesRow{}
	for rows.Next() {
		var i ListReleaseSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.VersionNum,
			&i.GitBranch,
			&i.GitCommit,
			&i.Notes,
			&i.Published,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.ArtifactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenDetails = `-- name: ListTokenDetails :many
SELECT t.id, t.name, t.token_prefix, t.project_id, t.scopes, t.expires_at, t.created_at, t.last_used_at,
       COALESCE(p.name, '') AS project_name
FROM api_tokens t
LEFT JOIN projects p ON t.project_id = p.id
ORDER BY t.created_at DESC
`

type ListTokenDetailsRow struct {
	ID          int64
	Name        string
	TokenPrefix string
	ProjectID   *int64
	Scopes      string
	ExpiresAt   *time.Time
	CreatedAt   time.Time
	LastUsedAt  *time.Time
	ProjectName string
}

func (q *Queries) ListTokenDetails(ctx context.Context) ([]ListTokenDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokenDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenDetailsRow{}
	for rows.Next() {
		var i ListTokenDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.ProjectID,
			&i.Scopes,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
