// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: artifacts.sql

package dbgen

import (
	"context"
	"database/sql"
)

const blobBelongsToProject = `-- name: BlobBelongsToProject :one
SELECT EXISTS(
    SELECT 1 FROM artifacts a
    JOIN releases r ON a.release_id = r.id
    WHERE r.project_id = ?1
    AND (a.storage_key = ?2 OR a.stripped_storage_key = ?2 OR a.debug_storage_key = ?2)
    UNION ALL
    SELECT 1 FROM packaged_artifacts pa
    JOIN artifacts a ON pa.artifact_id = a.id
    JOIN releases r ON a.release_id = r.id
    WHERE r.project_id = ?1 AND pa.storage_key = ?2
) AS blob_exists
`

type BlobBelongsToProjectParams struct {
	ProjectID  int64
	StorageKey string
}

func (q *Queries) BlobBelongsToProject(ctx context.Context, arg BlobBelongsToProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, blobBelongsToProject, arg.ProjectID, arg.StorageKey)
	var blob_exists int64
	err := row.Scan(&blob_exists)
	return blob_exists, err
}

const getArtifactByReleaseOSArch = `-- name: GetArtifactByReleaseOSArch :one
SELECT id, release_id, os, arch, kind, storage_key, size, sha256,
       stripped_storage_key, stripped_size, stripped_sha256,
       debug_storage_key, debug_size, filename, created_at
FROM artifacts WHERE release_id = ? AND os = ? AND arch = ?
`

type GetArtifactByReleaseOSArchParams struct {
	ReleaseID int64
	Os        string
	Arch      string
}

func (q *Queries) GetArtifactByReleaseOSArch(ctx context.Context, arg GetArtifactByReleaseOSArchParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByReleaseOSArch, arg.ReleaseID, arg.Os, arg.Arch)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Os,
		&i.Arch,
		&i.Kind,
		&i.StorageKey,
		&i.Size,
		&i.Sha256,
		&i.StrippedStorageKey,
		&i.StrippedSize,
		&i.StrippedSha256,
		&i.DebugStorageKey,
		&i.DebugSize,
		&i.Filename,
		&i.CreatedAt,
	)
	return i, err
}

const getPackagedArtifact = `-- name: GetPackagedArtifact :one
SELECT storage_key, size, sha256, filename FROM packaged_artifacts
WHERE artifact_id = ? AND format = ?
`

type GetPackagedArtifactParams struct {
	ArtifactID int64
	Format     string
}

type GetPackagedArtifactRow struct {
	StorageKey string
	Size       int64
	Sha256     string
	Filename   string
}

func (q *Queries) GetPackagedArtifact(ctx context.Context, arg GetPackagedArtifactParams) (GetPackagedArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, getPackagedArtifact, arg.ArtifactID, arg.Format)
	var i GetPackagedArtifactRow
	err := row.Scan(
		&i.StorageKey,
		&i.Size,
		&i.Sha256,
		&i.Filename,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :execresult
INSERT INTO artifacts (release_id, os, arch, kind, storage_key, size, sha256, filename)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertArtifactParams struct {
	ReleaseID  int64
	Os         string
	Arch       string
	Kind       string
	StorageKey string
	Size       int64
	Sha256     string
	Filename   string
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertArtifact,
		arg.ReleaseID,
		arg.Os,
		arg.Arch,
		arg.Kind,
		arg.StorageKey,
		arg.Size,
		arg.Sha256,
		arg.Filename,
	)
}

const listArtifactsByRelease = `-- name: ListArtifactsByRelease :many
SELECT id, release_id, os, arch, kind, storage_key, size, sha256,
       stripped_storage_key, stripped_size, stripped_sha256,
       debug_storage_key, debug_size, filename, created_at
FROM artifacts WHERE release_id = ?
`

func (q *Queries) ListArtifactsByRelease(ctx context.Context, releaseID int64) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.Os,
			&i.Arch,
			&i.Kind,
			&i.StorageKey,
			&i.Size,
			&i.Sha256,
			&i.StrippedStorageKey,
			&i.StrippedSize,
			&i.StrippedSha256,
			&i.DebugStorageKey,
			&i.DebugSize,
			&i.Filename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifactStripped = `-- name: UpdateArtifactStripped :exec
UPDATE artifacts SET stripped_storage_key = ?, stripped_size = ?, stripped_sha256 = ?,
 debug_storage_key = ?, debug_size = ?
WHERE id = ?
`

type UpdateArtifactStrippedParams struct {
	StrippedStorageKey string
	StrippedSize       int64
	StrippedSha256     string
	DebugStorageKey    string
	DebugSize          int64
	ID                 int64
}

func (q *Queries) UpdateArtifactStripped(ctx context.Context, arg UpdateArtifactStrippedParams) error {
	_, err := q.db.ExecContext(ctx, updateArtifactStripped,
		arg.StrippedStorageKey,
		arg.StrippedSize,
		arg.StrippedSha256,
		arg.DebugStorageKey,
		arg.DebugSize,
		arg.ID,
	)
	return err
}

const upsertPackagedArtifact = `-- name: UpsertPackagedArtifact :exec
INSERT OR REPLACE INTO packaged_artifacts (artifact_id, format, storage_key, size, sha256, filename, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type UpsertPackagedArtifactParams struct {
	ArtifactID int64
	Format     string
	StorageKey string
	Size       int64
	Sha256     string
	Filename   string
	Metadata   string
}

func (q *Queries) UpsertPackagedArtifact(ctx context.Context, arg UpsertPackagedArtifactParams) error {
	_, err := q.db.ExecContext(ctx, upsertPackagedArtifact,
		arg.ArtifactID,
		arg.Format,
		arg.StorageKey,
		arg.Size,
		arg.Sha256,
		arg.Filename,
		arg.Metadata,
	)
	return err
}
