// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"time"
)

type ApiToken struct {
	ID          int64
	Name        string
	TokenHash   string
	TokenPrefix string
	ProjectID   *int64
	Scopes      string
	ExpiresAt   *time.Time
	CreatedAt   time.Time
	LastUsedAt  *time.Time
}

type Artifact struct {
	ID                 int64
	ReleaseID          int64
	Os                 string
	Arch               string
	Kind               string
	StorageKey         string
	Size               int64
	Sha256             string
	StrippedStorageKey string
	StrippedSize       int64
	StrippedSha256     string
	DebugStorageKey    string
	DebugSize          int64
	Filename           string
	CreatedAt          time.Time
}

type DownloadCount struct {
	ArtifactID int64
	Count      int64
}

type OidcPolicy struct {
	ID             int64
	Issuer         string
	SubjectPattern string
	Audience       string
	ProjectID      *int64
	Scopes         string
	CreatedAt      time.Time
}

type PackagedArtifact struct {
	ID         int64
	ArtifactID int64
	Format     string
	StorageKey string
	Size       int64
	Sha256     string
	Filename   string
	Metadata   string
	CreatedAt  time.Time
}

type Project struct {
	ID          int64
	Name        string
	Description string
	Homepage    string
	License     string
	IsPrivate   bool
	Versioning  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Release struct {
	ID          int64
	ProjectID   int64
	Version     string
	VersionNum  int64
	GitBranch   string
	GitCommit   string
	Notes       string
	Published   bool
	CreatedAt   time.Time
	PublishedAt *time.Time
}
