package repackage

import (
	"bytes"
	"fmt"
	"io"
	"strings"
)

var apeMagic = []byte("MZqFpD='")

// peekAPE reports whether r begins with the APE prologue, returning a reader
// that still yields the full stream. Detection is a byte comparison: buildhost
// never executes an uploaded artifact to learn what it is.
func peekAPE(r io.Reader) (bool, io.Reader, error) {
	head := make([]byte, len(apeMagic))
	n, err := io.ReadFull(r, head)
	head = head[:n]
	rest := io.MultiReader(bytes.NewReader(head), r)
	if err != nil && err != io.ErrUnexpectedEOF && err != io.EOF {
		return false, rest, err
	}
	return bytes.Equal(head, apeMagic), rest, nil
}

// debAPELauncherPath is where an APE binary is installed when the package ships
func debAPELauncherTarget(pkgName string) string {
	return fmt.Sprintf("/usr/lib/%s/%s", pkgName, pkgName)
}

// debAPELauncher is the /usr/bin entry generated for an APE binary.
func debAPELauncher(pkgName, version string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by buildhost.\n")
	b.WriteString("#\n")
	b.WriteString("# " + pkgName + " is an Actually Portable Executable: it rewrites its own file\n")
	b.WriteString("# the first time it runs. A root-owned binary in /usr/bin cannot do that for\n")
	b.WriteString("# an ordinary user, so run a per-user writable copy instead.\n")
	b.WriteString("real=" + shellQuote(debAPELauncherTarget(pkgName)) + "\n")
	b.WriteString("dir=\"${XDG_CACHE_HOME:-${HOME:-/tmp}/.cache}/buildhost/" + pkgName + "/" + version + "\"\n")
	b.WriteString("bin=\"$dir/" + pkgName + "\"\n")
	b.WriteString("if [ ! -x \"$bin\" ]; then\n")
	b.WriteString("\tmkdir -p \"$dir\" 2>/dev/null || exec \"$real\" \"$@\"\n")
	b.WriteString("\ttmp=\"$bin.$$\"\n")
	b.WriteString("\tif cp \"$real\" \"$tmp\" 2>/dev/null && chmod 0755 \"$tmp\" 2>/dev/null && mv \"$tmp\" \"$bin\" 2>/dev/null; then\n")
	b.WriteString("\t\t:\n")
	b.WriteString("\telse\n")
	b.WriteString("\t\trm -f \"$tmp\" 2>/dev/null\n")
	b.WriteString("\t\texec \"$real\" \"$@\"\n")
	b.WriteString("\tfi\n")
	b.WriteString("fi\n")
	b.WriteString("exec \"$bin\" \"$@\"\n")
	return b.String()
}

// shellQuote renders s as a single-quoted shell word.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
