// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: admin.sql

package db

import (
	"context"
	"time"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM projects) AS project_count,
    (SELECT COUNT(*) FROM releases) AS release_count,
    (SELECT COUNT(*) FROM artifacts) AS artifact_count,
    CAST((SELECT COALESCE(SUM(size), 0) FROM artifacts) AS INTEGER) AS total_storage_bytes,
    (SELECT COUNT(*) FROM api_tokens) AS token_count,
    (SELECT COUNT(*) FROM oidc_policies) AS oidc_policy_count,
    (SELECT COUNT(*) FROM sites) AS site_count,
    CAST(
        (SELECT COALESCE(SUM(size), 0) FROM artifacts)
        + (SELECT COALESCE(SUM(CASE WHEN stripped_storage_key != '' THEN stripped_size ELSE 0 END), 0) FROM artifacts)
        + (SELECT COALESCE(SUM(CASE WHEN debug_storage_key != '' THEN debug_size ELSE 0 END), 0) FROM artifacts)
        + (SELECT COALESCE(SUM(size), 0) FROM packaged_artifacts)
    AS INTEGER) AS logical_bytes,
    CAST((SELECT COALESCE(SUM(sz), 0) FROM (
        SELECT k, MAX(sz) AS sz FROM (
            SELECT storage_key AS k, size AS sz FROM artifacts
            UNION ALL
            SELECT stripped_storage_key, stripped_size FROM artifacts WHERE stripped_storage_key != ''
            UNION ALL
            SELECT debug_storage_key, debug_size FROM artifacts WHERE debug_storage_key != ''
            UNION ALL
            SELECT storage_key, size FROM packaged_artifacts
        ) GROUP BY k
    )) AS INTEGER) AS physical_bytes
`

type GetDashboardStatsRow struct {
	ProjectCount      int64 `json:"project_count"`
	ReleaseCount      int64 `json:"release_count"`
	ArtifactCount     int64 `json:"artifact_count"`
	TotalStorageBytes int64 `json:"total_storage_bytes"`
	TokenCount        int64 `json:"token_count"`
	OidcPolicyCount   int64 `json:"oidc_policy_count"`
	SiteCount         int64 `json:"site_count"`
	LogicalBytes      int64 `json:"logical_bytes"`
	PhysicalBytes     int64 `json:"physical_bytes"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.ProjectCount,
		&i.ReleaseCount,
		&i.ArtifactCount,
		&i.TotalStorageBytes,
		&i.TokenCount,
		&i.OidcPolicyCount,
		&i.SiteCount,
		&i.LogicalBytes,
		&i.PhysicalBytes,
	)
	return i, err
}

const getStorageBreakdown = `-- name: GetStorageBreakdown :many
SELECT p.id, p.name,
       CAST(COALESCE(SUM(a.size), 0) AS INTEGER) AS total_bytes,
       COUNT(a.id) AS artifact_count,
       COUNT(DISTINCT r.id) AS release_count
FROM projects p
LEFT JOIN releases r ON r.project_id = p.id
LEFT JOIN artifacts a ON a.release_id = r.id
GROUP BY p.id, p.name
ORDER BY total_bytes DESC
`

type GetStorageBreakdownRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	TotalBytes    int64  `json:"total_bytes"`
	ArtifactCount int64  `json:"artifact_count"`
	ReleaseCount  int64  `json:"release_count"`
}

func (q *Queries) GetStorageBreakdown(ctx context.Context) ([]GetStorageBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getStorageBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStorageBreakdownRow{}
	for rows.Next() {
		var i GetStorageBreakdownRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TotalBytes,
			&i.ArtifactCount,
			&i.ReleaseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllArtifacts = `-- name: ListAllArtifacts :many
SELECT a.id, a.os, a.arch, a.kind, a.size, a.filename, a.created_at,
       r.version, r.git_branch,
       p.name AS project_name,
       CAST(COALESCE(dc.count, 0) AS INTEGER) AS download_count
FROM artifacts a
JOIN releases r ON a.release_id = r.id
JOIN projects p ON r.project_id = p.id
LEFT JOIN download_counts dc ON dc.artifact_id = a.id
ORDER BY a.created_at DESC, a.id DESC
`

type ListAllArtifactsRow struct {
	ID            int64     `json:"id"`
	OS            OS        `json:"os"`
	Arch          Arch      `json:"arch"`
	Kind          Kind      `json:"kind"`
	Size          int64     `json:"size"`
	Filename      string    `json:"filename"`
	CreatedAt     time.Time `json:"created_at"`
	Version       string    `json:"version"`
	GitBranch     string    `json:"git_branch"`
	ProjectName   string    `json:"project_name"`
	DownloadCount int64     `json:"download_count"`
}

func (q *Queries) ListAllArtifacts(ctx context.Context) ([]ListAllArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllArtifactsRow{}
	for rows.Next() {
		var i ListAllArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.OS,
			&i.Arch,
			&i.Kind,
			&i.Size,
			&i.Filename,
			&i.CreatedAt,
			&i.Version,
			&i.GitBranch,
			&i.ProjectName,
			&i.DownloadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCPolicyDetails = `-- name: ListOIDCPolicyDetails :many
SELECT o.id, o.issuer, o.subject_pattern, o.audience, o.project_id, o.scopes, o.created_at,
       COALESCE(p.name, '') AS project_name
FROM oidc_policies o
LEFT JOIN projects p ON o.project_id = p.id
ORDER BY o.created_at DESC
`

type ListOIDCPolicyDetailsRow struct {
	ID             int64     `json:"id"`
	Issuer         string    `json:"issuer"`
	SubjectPattern string    `json:"subject_pattern"`
	Audience       string    `json:"audience"`
	ProjectID      *int64    `json:"project_id"`
	Scopes         string    `json:"scopes"`
	CreatedAt      time.Time `json:"created_at"`
	ProjectName    string    `json:"project_name"`
}

func (q *Queries) ListOIDCPolicyDetails(ctx context.Context) ([]ListOIDCPolicyDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOIDCPolicyDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOIDCPolicyDetailsRow{}
	for rows.Next() {
		var i ListOIDCPolicyDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.SubjectPattern,
			&i.Audience,
			&i.ProjectID,
			&i.Scopes,
			&i.CreatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectSummaries = `-- name: ListProjectSummaries :many
SELECT p.id, p.name, p.description, p.homepage, p.license, p.is_private, p.versioning,
       p.created_at, p.updated_at,
       (SELECT COUNT(*) FROM releases WHERE project_id = p.id) AS release_count,
       (SELECT COUNT(*) FROM artifacts a JOIN releases r ON a.release_id = r.id WHERE r.project_id = p.id) AS artifact_count,
       (SELECT COUNT(*) FROM sites WHERE project_id = p.id) AS site_count
FROM projects p
ORDER BY p.name
`

type ListProjectSummariesRow struct {
	ID            int64      `json:"id"`
	Name          string     `json:"name"`
	Description   string     `json:"description"`
	Homepage      string     `json:"homepage"`
	License       string     `json:"license"`
	IsPrivate     bool       `json:"is_private"`
	Versioning    Versioning `json:"versioning"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	ReleaseCount  int64      `json:"release_count"`
	ArtifactCount int64      `json:"artifact_count"`
	SiteCount     int64      `json:"site_count"`
}

func (q *Queries) ListProjectSummaries(ctx context.Context) ([]ListProjectSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectSummariesRow{}
	for rows.Next() {
		var i ListProjectSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Homepage,
			&i.License,
			&i.IsPrivate,
			&i.Versioning,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleaseCount,
			&i.ArtifactCount,
			&i.SiteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentReleases = `-- name: ListRecentReleases :many
SELECT r.id, r.project_id, r.version, r.version_num, r.git_branch, r.git_commit,
       r.notes, r.published, r.created_at, r.published_at, p.name AS project_name
FROM releases r
JOIN projects p ON r.project_id = p.id
ORDER BY r.created_at DESC, r.id DESC
LIMIT ?
`

type ListRecentReleasesRow struct {
	ID          int64      `json:"id"`
	ProjectID   int64      `json:"project_id"`
	Version     string     `json:"version"`
	VersionNum  int64      `json:"version_num"`
	GitBranch   string     `json:"git_branch"`
	GitCommit   string     `json:"git_commit"`
	Notes       string     `json:"notes"`
	Published   bool       `json:"published"`
	CreatedAt   time.Time  `json:"created_at"`
	PublishedAt *time.Time `json:"published_at"`
	ProjectName string     `json:"project_name"`
}

func (q *Queries) ListRecentReleases(ctx context.Context, limit int64) ([]ListRecentReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentReleases, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentReleasesRow{}
	for rows.Next() {
		var i ListRecentReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.VersionNum,
			&i.GitBranch,
			&i.GitCommit,
			&i.Notes,
			&i.Published,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseSummaries = `-- name: ListReleaseSummaries :many
SELECT r.id, r.project_id, r.version, r.version_num, r.git_branch, r.git_commit,
       r.notes, r.published, r.created_at, r.published_at,
       (SELECT COUNT(*) FROM artifacts WHERE release_id = r.id) AS artifact_count
FROM releases r
WHERE r.project_id = ?
ORDER BY r.version_num DESC
`

type ListReleaseSummariesRow struct {
	ID            int64      `json:"id"`
	ProjectID     int64      `json:"project_id"`
	Version       string     `json:"version"`
	VersionNum    int64      `json:"version_num"`
	GitBranch     string     `json:"git_branch"`
	GitCommit     string     `json:"git_commit"`
	Notes         string     `json:"notes"`
	Published     bool       `json:"published"`
	CreatedAt     time.Time  `json:"created_at"`
	PublishedAt   *time.Time `json:"published_at"`
	ArtifactCount int64      `json:"artifact_count"`
}

func (q *Queries) ListReleaseSummaries(ctx context.Context, projectID int64) ([]ListReleaseSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseSummaries, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseSummariesRow{}
	for rows.Next() {
		var i ListReleaseSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.VersionNum,
			&i.GitBranch,
			&i.GitCommit,
			&i.Notes,
			&i.Published,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.ArtifactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteDetails = `-- name: ListSiteDetails :many
SELECT s.id, s.project_id, s.branch, s.storage_key, s.size, s.sha256,
       s.file_count, s.git_commit, s.created_at, s.updated_at,
       p.name AS project_name
FROM sites s
JOIN projects p ON s.project_id = p.id
ORDER BY s.updated_at DESC
`

type ListSiteDetailsRow struct {
	ID          int64     `json:"id"`
	ProjectID   int64     `json:"project_id"`
	Branch      string    `json:"branch"`
	StorageKey  string    `json:"storage_key"`
	Size        int64     `json:"size"`
	SHA256      string    `json:"sha256"`
	FileCount   int64     `json:"file_count"`
	GitCommit   string    `json:"git_commit"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ProjectName string    `json:"project_name"`
}

func (q *Queries) ListSiteDetails(ctx context.Context) ([]ListSiteDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSiteDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteDetailsRow{}
	for rows.Next() {
		var i ListSiteDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Branch,
			&i.StorageKey,
			&i.Size,
			&i.SHA256,
			&i.FileCount,
			&i.GitCommit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenDetails = `-- name: ListTokenDetails :many
SELECT t.id, t.name, t.token_prefix, t.project_id, t.scopes, t.expires_at, t.created_at, t.last_used_at,
       COALESCE(p.name, '') AS project_name
FROM api_tokens t
LEFT JOIN projects p ON t.project_id = p.id
ORDER BY t.created_at DESC
`

type ListTokenDetailsRow struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	TokenPrefix string     `json:"token_prefix"`
	ProjectID   *int64     `json:"project_id"`
	Scopes      string     `json:"scopes"`
	ExpiresAt   *time.Time `json:"expires_at"`
	CreatedAt   time.Time  `json:"created_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
	ProjectName string     `json:"project_name"`
}

func (q *Queries) ListTokenDetails(ctx context.Context) ([]ListTokenDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTokenDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTokenDetailsRow{}
	for rows.Next() {
		var i ListTokenDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.ProjectID,
			&i.Scopes,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
