// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: artifacts.sql

package db

import (
	"context"
	"database/sql"
)

const blobBelongsToProject = `-- name: BlobBelongsToProject :one
SELECT EXISTS(
    SELECT 1 FROM artifacts a
    JOIN releases r ON a.release_id = r.id
    WHERE r.project_id = ?1
    AND (a.storage_key = ?2 OR a.stripped_storage_key = ?2 OR a.debug_storage_key = ?2)
    UNION ALL
    SELECT 1 FROM packaged_artifacts pa
    JOIN artifacts a ON pa.artifact_id = a.id
    JOIN releases r ON a.release_id = r.id
    WHERE r.project_id = ?1 AND pa.storage_key = ?2
    UNION ALL
    SELECT 1 FROM oci_blob_links obl
    WHERE obl.project_id = ?1 AND obl.storage_key = ?2
) AS blob_exists
`

type BlobBelongsToProjectParams struct {
	ProjectID  int64  `json:"project_id"`
	StorageKey string `json:"storage_key"`
}

func (q *Queries) BlobBelongsToProject(ctx context.Context, arg BlobBelongsToProjectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, blobBelongsToProject, arg.ProjectID, arg.StorageKey)
	var blob_exists int64
	err := row.Scan(&blob_exists)
	return blob_exists, err
}

const deleteReleaseArtifactPlatforms = `-- name: DeleteReleaseArtifactPlatforms :exec
DELETE FROM artifact_platforms WHERE release_id = ?
`

func (q *Queries) DeleteReleaseArtifactPlatforms(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseArtifactPlatforms, releaseID)
	return err
}

const getArtifactByReleaseAndKind = `-- name: GetArtifactByReleaseAndKind :one
SELECT id, release_id, os, arch, kind, storage_key, size, sha256,
       stripped_storage_key, stripped_size, stripped_sha256,
       debug_storage_key, debug_size, filename, exe_format, created_at
FROM artifacts WHERE release_id = ? AND kind = ?
`

type GetArtifactByReleaseAndKindParams struct {
	ReleaseID int64 `json:"release_id"`
	Kind      Kind  `json:"kind"`
}

func (q *Queries) GetArtifactByReleaseAndKind(ctx context.Context, arg GetArtifactByReleaseAndKindParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByReleaseAndKind, arg.ReleaseID, arg.Kind)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.OS,
		&i.Arch,
		&i.Kind,
		&i.StorageKey,
		&i.Size,
		&i.SHA256,
		&i.StrippedStorageKey,
		&i.StrippedSize,
		&i.StrippedSHA256,
		&i.DebugStorageKey,
		&i.DebugSize,
		&i.Filename,
		&i.ExeFormat,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactByReleaseOSArch = `-- name: GetArtifactByReleaseOSArch :one
SELECT a.id, a.release_id, a.os, a.arch, a.kind, a.storage_key, a.size, a.sha256,
       a.stripped_storage_key, a.stripped_size, a.stripped_sha256,
       a.debug_storage_key, a.debug_size, a.filename, a.exe_format, a.created_at
FROM artifacts a
JOIN artifact_platforms p ON p.artifact_id = a.id
WHERE p.release_id = ? AND p.os = ? AND p.arch = ?
ORDER BY a.id
`

type GetArtifactByReleaseOSArchParams struct {
	ReleaseID int64  `json:"release_id"`
	OS        string `json:"os"`
	Arch      string `json:"arch"`
}

// Resolution goes through artifact_platforms, which holds every slot an
// artifact occupies -- one row for an ordinary per-platform upload, N for a
// multi-platform one. Every covered platform therefore resolves to the same
// artifact, hence the same blob, digest and ETag.
func (q *Queries) GetArtifactByReleaseOSArch(ctx context.Context, arg GetArtifactByReleaseOSArchParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByReleaseOSArch, arg.ReleaseID, arg.OS, arg.Arch)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.OS,
		&i.Arch,
		&i.Kind,
		&i.StorageKey,
		&i.Size,
		&i.SHA256,
		&i.StrippedStorageKey,
		&i.StrippedSize,
		&i.StrippedSHA256,
		&i.DebugStorageKey,
		&i.DebugSize,
		&i.Filename,
		&i.ExeFormat,
		&i.CreatedAt,
	)
	return i, err
}

const getPackagedArtifact = `-- name: GetPackagedArtifact :one
SELECT storage_key, size, sha256, filename, metadata FROM packaged_artifacts
WHERE artifact_id = ? AND format = ?
`

type GetPackagedArtifactParams struct {
	ArtifactID int64  `json:"artifact_id"`
	Format     string `json:"format"`
}

type GetPackagedArtifactRow struct {
	StorageKey string `json:"storage_key"`
	Size       int64  `json:"size"`
	SHA256     string `json:"sha256"`
	Filename   string `json:"filename"`
	Metadata   string `json:"metadata"`
}

func (q *Queries) GetPackagedArtifact(ctx context.Context, arg GetPackagedArtifactParams) (GetPackagedArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, getPackagedArtifact, arg.ArtifactID, arg.Format)
	var i GetPackagedArtifactRow
	err := row.Scan(
		&i.StorageKey,
		&i.Size,
		&i.SHA256,
		&i.Filename,
		&i.Metadata,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :execresult
INSERT INTO artifacts (release_id, os, arch, kind, storage_key, size, sha256, filename, exe_format)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertArtifactParams struct {
	ReleaseID  int64  `json:"release_id"`
	OS         OS     `json:"os"`
	Arch       Arch   `json:"arch"`
	Kind       Kind   `json:"kind"`
	StorageKey string `json:"storage_key"`
	Size       int64  `json:"size"`
	SHA256     string `json:"sha256"`
	Filename   string `json:"filename"`
	ExeFormat  string `json:"exe_format"`
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertArtifact,
		arg.ReleaseID,
		arg.OS,
		arg.Arch,
		arg.Kind,
		arg.StorageKey,
		arg.Size,
		arg.SHA256,
		arg.Filename,
		arg.ExeFormat,
	)
}

const insertArtifactPlatform = `-- name: InsertArtifactPlatform :exec
INSERT INTO artifact_platforms (artifact_id, release_id, kind, os, arch, ordinal)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertArtifactPlatformParams struct {
	ArtifactID int64  `json:"artifact_id"`
	ReleaseID  int64  `json:"release_id"`
	Kind       string `json:"kind"`
	OS         string `json:"os"`
	Arch       string `json:"arch"`
	Ordinal    int64  `json:"ordinal"`
}

func (q *Queries) InsertArtifactPlatform(ctx context.Context, arg InsertArtifactPlatformParams) error {
	_, err := q.db.ExecContext(ctx, insertArtifactPlatform,
		arg.ArtifactID,
		arg.ReleaseID,
		arg.Kind,
		arg.OS,
		arg.Arch,
		arg.Ordinal,
	)
	return err
}

const listArtifactPlatformsByArtifact = `-- name: ListArtifactPlatformsByArtifact :many
SELECT os, arch FROM artifact_platforms WHERE artifact_id = ? ORDER BY ordinal
`

type ListArtifactPlatformsByArtifactRow struct {
	OS   string `json:"os"`
	Arch string `json:"arch"`
}

func (q *Queries) ListArtifactPlatformsByArtifact(ctx context.Context, artifactID int64) ([]ListArtifactPlatformsByArtifactRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactPlatformsByArtifact, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactPlatformsByArtifactRow{}
	for rows.Next() {
		var i ListArtifactPlatformsByArtifactRow
		if err := rows.Scan(&i.OS, &i.Arch); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactPlatformsByRelease = `-- name: ListArtifactPlatformsByRelease :many
SELECT artifact_id, os, arch FROM artifact_platforms
WHERE release_id = ? ORDER BY artifact_id, ordinal
`

type ListArtifactPlatformsByReleaseRow struct {
	ArtifactID int64  `json:"artifact_id"`
	OS         string `json:"os"`
	Arch       string `json:"arch"`
}

func (q *Queries) ListArtifactPlatformsByRelease(ctx context.Context, releaseID int64) ([]ListArtifactPlatformsByReleaseRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactPlatformsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactPlatformsByReleaseRow{}
	for rows.Next() {
		var i ListArtifactPlatformsByReleaseRow
		if err := rows.Scan(&i.ArtifactID, &i.OS, &i.Arch); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByRelease = `-- name: ListArtifactsByRelease :many
SELECT id, release_id, os, arch, kind, storage_key, size, sha256,
       stripped_storage_key, stripped_size, stripped_sha256,
       debug_storage_key, debug_size, filename, exe_format, created_at
FROM artifacts WHERE release_id = ?
`

func (q *Queries) ListArtifactsByRelease(ctx context.Context, releaseID int64) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.OS,
			&i.Arch,
			&i.Kind,
			&i.StorageKey,
			&i.Size,
			&i.SHA256,
			&i.StrippedStorageKey,
			&i.StrippedSize,
			&i.StrippedSHA256,
			&i.DebugStorageKey,
			&i.DebugSize,
			&i.Filename,
			&i.ExeFormat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtifactStripped = `-- name: UpdateArtifactStripped :exec
UPDATE artifacts SET stripped_storage_key = ?, stripped_size = ?, stripped_sha256 = ?,
 debug_storage_key = ?, debug_size = ?
WHERE id = ?
`

type UpdateArtifactStrippedParams struct {
	StrippedStorageKey string `json:"stripped_storage_key"`
	StrippedSize       int64  `json:"stripped_size"`
	StrippedSHA256     string `json:"stripped_sha256"`
	DebugStorageKey    string `json:"debug_storage_key"`
	DebugSize          int64  `json:"debug_size"`
	ID                 int64  `json:"id"`
}

func (q *Queries) UpdateArtifactStripped(ctx context.Context, arg UpdateArtifactStrippedParams) error {
	_, err := q.db.ExecContext(ctx, updateArtifactStripped,
		arg.StrippedStorageKey,
		arg.StrippedSize,
		arg.StrippedSHA256,
		arg.DebugStorageKey,
		arg.DebugSize,
		arg.ID,
	)
	return err
}

const upsertPackagedArtifact = `-- name: UpsertPackagedArtifact :exec
INSERT OR REPLACE INTO packaged_artifacts (artifact_id, format, storage_key, size, sha256, filename, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type UpsertPackagedArtifactParams struct {
	ArtifactID int64  `json:"artifact_id"`
	Format     string `json:"format"`
	StorageKey string `json:"storage_key"`
	Size       int64  `json:"size"`
	SHA256     string `json:"sha256"`
	Filename   string `json:"filename"`
	Metadata   string `json:"metadata"`
}

func (q *Queries) UpsertPackagedArtifact(ctx context.Context, arg UpsertPackagedArtifactParams) error {
	_, err := q.db.ExecContext(ctx, upsertPackagedArtifact,
		arg.ArtifactID,
		arg.Format,
		arg.StorageKey,
		arg.Size,
		arg.SHA256,
		arg.Filename,
		arg.Metadata,
	)
	return err
}
