// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: deleted_branches.sql

package db

import (
	"context"
)

const clearBranchDeleted = `-- name: ClearBranchDeleted :exec
DELETE FROM deleted_branches WHERE project_id = ? AND branch = ?
`

type ClearBranchDeletedParams struct {
	ProjectID int64  `json:"project_id"`
	Branch    string `json:"branch"`
}

func (q *Queries) ClearBranchDeleted(ctx context.Context, arg ClearBranchDeletedParams) error {
	_, err := q.db.ExecContext(ctx, clearBranchDeleted, arg.ProjectID, arg.Branch)
	return err
}

const clearBranchDeletedForRepo = `-- name: ClearBranchDeletedForRepo :exec
DELETE FROM deleted_branches
WHERE branch = ?1
  AND project_id IN (SELECT p.id FROM projects p WHERE lower(p.github_repo) = lower(?2))
`

type ClearBranchDeletedForRepoParams struct {
	Branch     string `json:"branch"`
	GithubRepo string `json:"github_repo"`
}

func (q *Queries) ClearBranchDeletedForRepo(ctx context.Context, arg ClearBranchDeletedForRepoParams) error {
	_, err := q.db.ExecContext(ctx, clearBranchDeletedForRepo, arg.Branch, arg.GithubRepo)
	return err
}

const deleteProjectDeletedBranches = `-- name: DeleteProjectDeletedBranches :exec
DELETE FROM deleted_branches WHERE project_id = ?
`

func (q *Queries) DeleteProjectDeletedBranches(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectDeletedBranches, projectID)
	return err
}

const listDeletedBranches = `-- name: ListDeletedBranches :many
SELECT project_id, branch, deleted_at FROM deleted_branches WHERE project_id = ? ORDER BY branch
`

func (q *Queries) ListDeletedBranches(ctx context.Context, projectID int64) ([]DeletedBranch, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedBranches, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeletedBranch{}
	for rows.Next() {
		var i DeletedBranch
		if err := rows.Scan(&i.ProjectID, &i.Branch, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubRepoProjects = `-- name: ListGitHubRepoProjects :many
SELECT id, name, github_repo, default_branch FROM projects WHERE github_repo != '' ORDER BY id
`

type ListGitHubRepoProjectsRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	GithubRepo    string `json:"github_repo"`
	DefaultBranch string `json:"default_branch"`
}

// Every project tied to a GitHub repo, which is every project the branch sync
// can check.
func (q *Queries) ListGitHubRepoProjects(ctx context.Context) ([]ListGitHubRepoProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGitHubRepoProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGitHubRepoProjectsRow{}
	for rows.Next() {
		var i ListGitHubRepoProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GithubRepo,
			&i.DefaultBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectReleaseBranches = `-- name: ListProjectReleaseBranches :many
SELECT DISTINCT git_branch FROM releases WHERE project_id = ? AND git_branch != '' ORDER BY git_branch
`

// The distinct branches a project holds releases on.
func (q *Queries) ListProjectReleaseBranches(ctx context.Context, projectID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectReleaseBranches, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var git_branch string
		if err := rows.Scan(&git_branch); err != nil {
			return nil, err
		}
		items = append(items, git_branch)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBranchDeleted = `-- name: RecordBranchDeleted :exec
INSERT OR IGNORE INTO deleted_branches (project_id, branch, deleted_at)
VALUES (?1, ?2, datetime(?3))
`

type RecordBranchDeletedParams struct {
	ProjectID int64       `json:"project_id"`
	Branch    string      `json:"branch"`
	DeletedAt interface{} `json:"deleted_at"`
}

func (q *Queries) RecordBranchDeleted(ctx context.Context, arg RecordBranchDeletedParams) error {
	_, err := q.db.ExecContext(ctx, recordBranchDeleted, arg.ProjectID, arg.Branch, arg.DeletedAt)
	return err
}

const recordBranchDeletedForRepo = `-- name: RecordBranchDeletedForRepo :exec
INSERT OR IGNORE INTO deleted_branches (project_id, branch, deleted_at)
SELECT p.id, ?1, datetime(?2)
FROM projects p
WHERE lower(p.github_repo) = lower(?3)
`

type RecordBranchDeletedForRepoParams struct {
	Branch     string      `json:"branch"`
	DeletedAt  interface{} `json:"deleted_at"`
	GithubRepo string      `json:"github_repo"`
}

// Marks the branch deleted on every project the GitHub repo owns. OR IGNORE
// keeps the first deletion time, so a repeated delivery does not restart the TTL.
func (q *Queries) RecordBranchDeletedForRepo(ctx context.Context, arg RecordBranchDeletedForRepoParams) error {
	_, err := q.db.ExecContext(ctx, recordBranchDeletedForRepo, arg.Branch, arg.DeletedAt, arg.GithubRepo)
	return err
}
