// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: download_events.sql

package db

import (
	"context"
	"time"
)

const listDownloadEventsByProject = `-- name: ListDownloadEventsByProject :many
SELECT de.id, de.artifact_id, de.fmt, de.client_ip, de.user_agent, de.principal, de.created_at,
       a.os, a.arch, r.version, r.git_branch
FROM download_events de
JOIN artifacts a ON de.artifact_id = a.id
JOIN releases r ON a.release_id = r.id
WHERE r.project_id = ?
ORDER BY de.created_at DESC, de.id DESC
LIMIT ?
`

type ListDownloadEventsByProjectParams struct {
	ProjectID int64 `json:"project_id"`
	Limit     int64 `json:"limit"`
}

type ListDownloadEventsByProjectRow struct {
	ID         int64     `json:"id"`
	ArtifactID int64     `json:"artifact_id"`
	Fmt        string    `json:"fmt"`
	ClientIp   string    `json:"client_ip"`
	UserAgent  string    `json:"user_agent"`
	Principal  string    `json:"principal"`
	CreatedAt  time.Time `json:"created_at"`
	OS         OS        `json:"os"`
	Arch       Arch      `json:"arch"`
	Version    string    `json:"version"`
	GitBranch  string    `json:"git_branch"`
}

func (q *Queries) ListDownloadEventsByProject(ctx context.Context, arg ListDownloadEventsByProjectParams) ([]ListDownloadEventsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadEventsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDownloadEventsByProjectRow{}
	for rows.Next() {
		var i ListDownloadEventsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Fmt,
			&i.ClientIp,
			&i.UserAgent,
			&i.Principal,
			&i.CreatedAt,
			&i.OS,
			&i.Arch,
			&i.Version,
			&i.GitBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadEventsByRelease = `-- name: ListDownloadEventsByRelease :many
SELECT de.id, de.artifact_id, de.fmt, de.client_ip, de.user_agent, de.principal, de.created_at,
       a.os, a.arch
FROM download_events de
JOIN artifacts a ON de.artifact_id = a.id
WHERE a.release_id = ?
ORDER BY de.created_at DESC, de.id DESC
LIMIT ?
`

type ListDownloadEventsByReleaseParams struct {
	ReleaseID int64 `json:"release_id"`
	Limit     int64 `json:"limit"`
}

type ListDownloadEventsByReleaseRow struct {
	ID         int64     `json:"id"`
	ArtifactID int64     `json:"artifact_id"`
	Fmt        string    `json:"fmt"`
	ClientIp   string    `json:"client_ip"`
	UserAgent  string    `json:"user_agent"`
	Principal  string    `json:"principal"`
	CreatedAt  time.Time `json:"created_at"`
	OS         OS        `json:"os"`
	Arch       Arch      `json:"arch"`
}

func (q *Queries) ListDownloadEventsByRelease(ctx context.Context, arg ListDownloadEventsByReleaseParams) ([]ListDownloadEventsByReleaseRow, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadEventsByRelease, arg.ReleaseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDownloadEventsByReleaseRow{}
	for rows.Next() {
		var i ListDownloadEventsByReleaseRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Fmt,
			&i.ClientIp,
			&i.UserAgent,
			&i.Principal,
			&i.CreatedAt,
			&i.OS,
			&i.Arch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDownloadEvent = `-- name: RecordDownloadEvent :exec
INSERT INTO download_events (artifact_id, fmt, client_ip, user_agent, principal)
VALUES (?, ?, ?, ?, ?)
`

type RecordDownloadEventParams struct {
	ArtifactID int64  `json:"artifact_id"`
	Fmt        string `json:"fmt"`
	ClientIp   string `json:"client_ip"`
	UserAgent  string `json:"user_agent"`
	Principal  string `json:"principal"`
}

func (q *Queries) RecordDownloadEvent(ctx context.Context, arg RecordDownloadEventParams) error {
	_, err := q.db.ExecContext(ctx, recordDownloadEvent,
		arg.ArtifactID,
		arg.Fmt,
		arg.ClientIp,
		arg.UserAgent,
		arg.Principal,
	)
	return err
}
