// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: download_counts.sql

package db

import (
	"context"
	"time"
)

const getTotalDownloads = `-- name: GetTotalDownloads :one
SELECT CAST(COALESCE(SUM(dc.count), 0) AS INTEGER) AS total
FROM download_counts dc
JOIN artifacts a ON dc.artifact_id = a.id
WHERE a.release_id = ?
`

func (q *Queries) GetTotalDownloads(ctx context.Context, releaseID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalDownloads, releaseID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const incrementDownloadCount = `-- name: IncrementDownloadCount :exec
INSERT INTO download_counts (artifact_id, count) VALUES (?, 1)
ON CONFLICT(artifact_id) DO UPDATE SET count = count + 1
`

func (q *Queries) IncrementDownloadCount(ctx context.Context, artifactID int64) error {
	_, err := q.db.ExecContext(ctx, incrementDownloadCount, artifactID)
	return err
}

const listArtifactDetailsWithDownloads = `-- name: ListArtifactDetailsWithDownloads :many
SELECT a.id, a.release_id, a.os, a.arch, a.kind, a.storage_key, a.size, a.sha256,
       a.stripped_storage_key, a.stripped_size, a.stripped_sha256,
       a.debug_storage_key, a.debug_size, a.filename, a.created_at,
       CAST(COALESCE(dc.count, 0) AS INTEGER) AS download_count
FROM artifacts a
LEFT JOIN download_counts dc ON dc.artifact_id = a.id
WHERE a.release_id = ?
ORDER BY a.os, a.arch, a.kind
`

type ListArtifactDetailsWithDownloadsRow struct {
	ID                 int64     `json:"id"`
	ReleaseID          int64     `json:"release_id"`
	OS                 OS        `json:"os"`
	Arch               Arch      `json:"arch"`
	Kind               Kind      `json:"kind"`
	StorageKey         string    `json:"storage_key"`
	Size               int64     `json:"size"`
	SHA256             string    `json:"sha256"`
	StrippedStorageKey string    `json:"stripped_storage_key"`
	StrippedSize       int64     `json:"stripped_size"`
	StrippedSHA256     string    `json:"stripped_sha256"`
	DebugStorageKey    string    `json:"debug_storage_key"`
	DebugSize          int64     `json:"debug_size"`
	Filename           string    `json:"filename"`
	CreatedAt          time.Time `json:"created_at"`
	DownloadCount      int64     `json:"download_count"`
}

func (q *Queries) ListArtifactDetailsWithDownloads(ctx context.Context, releaseID int64) ([]ListArtifactDetailsWithDownloadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactDetailsWithDownloads, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactDetailsWithDownloadsRow{}
	for rows.Next() {
		var i ListArtifactDetailsWithDownloadsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.OS,
			&i.Arch,
			&i.Kind,
			&i.StorageKey,
			&i.Size,
			&i.SHA256,
			&i.StrippedStorageKey,
			&i.StrippedSize,
			&i.StrippedSHA256,
			&i.DebugStorageKey,
			&i.DebugSize,
			&i.Filename,
			&i.CreatedAt,
			&i.DownloadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagedFormats = `-- name: ListPackagedFormats :many
SELECT format, size, sha256, filename FROM packaged_artifacts
WHERE artifact_id = ? ORDER BY format
`

type ListPackagedFormatsRow struct {
	Format   string `json:"format"`
	Size     int64  `json:"size"`
	SHA256   string `json:"sha256"`
	Filename string `json:"filename"`
}

func (q *Queries) ListPackagedFormats(ctx context.Context, artifactID int64) ([]ListPackagedFormatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPackagedFormats, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagedFormatsRow{}
	for rows.Next() {
		var i ListPackagedFormatsRow
		if err := rows.Scan(
			&i.Format,
			&i.Size,
			&i.SHA256,
			&i.Filename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
