// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: goproxy.sql

package db

import (
	"context"
	"time"
)

const getGoproxyCacheStats = `-- name: GetGoproxyCacheStats :one
SELECT
    (SELECT COUNT(*) FROM goproxy_modules)                                   AS modules,
    (SELECT COUNT(*) FROM goproxy_versions)                                  AS versions,
    (SELECT COUNT(*) FROM goproxy_versions WHERE zip_storage_key != '')      AS zips,
    (SELECT COALESCE(SUM(zip_size), 0) FROM goproxy_versions)                AS bytes,
    (SELECT COUNT(*) FROM goproxy_modules WHERE last_error_kind != '')       AS failing_modules
`

type GetGoproxyCacheStatsRow struct {
	Modules        int64       `json:"modules"`
	Versions       int64       `json:"versions"`
	Zips           int64       `json:"zips"`
	Bytes          interface{} `json:"bytes"`
	FailingModules int64       `json:"failing_modules"`
}

func (q *Queries) GetGoproxyCacheStats(ctx context.Context) (GetGoproxyCacheStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getGoproxyCacheStats)
	var i GetGoproxyCacheStatsRow
	err := row.Scan(
		&i.Modules,
		&i.Versions,
		&i.Zips,
		&i.Bytes,
		&i.FailingModules,
	)
	return i, err
}

const getGoproxyVersion = `-- name: GetGoproxyVersion :one
SELECT v.id, v.module_id, v.version, v.commit_sha, v.committed_at, v.go_mod,
       v.zip_storage_key, v.zip_size, v.fetched_at
FROM goproxy_versions v
JOIN goproxy_modules m ON m.id = v.module_id
WHERE m.module_path = ? AND v.version = ?
`

type GetGoproxyVersionParams struct {
	ModulePath string `json:"module_path"`
	Version    string `json:"version"`
}

func (q *Queries) GetGoproxyVersion(ctx context.Context, arg GetGoproxyVersionParams) (GoproxyVersion, error) {
	row := q.db.QueryRowContext(ctx, getGoproxyVersion, arg.ModulePath, arg.Version)
	var i GoproxyVersion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Version,
		&i.CommitSha,
		&i.CommittedAt,
		&i.GoMod,
		&i.ZipStorageKey,
		&i.ZipSize,
		&i.FetchedAt,
	)
	return i, err
}

const listGoproxyModuleSummaries = `-- name: ListGoproxyModuleSummaries :many
SELECT m.module_path, m.source, m.last_error_kind, m.last_error, m.last_error_at, m.last_success_at,
       COUNT(v.id)                       AS version_count,
       COALESCE(SUM(v.zip_size), 0)      AS bytes,
       MAX(v.fetched_at)                 AS last_fetched_at
FROM goproxy_modules m
LEFT JOIN goproxy_versions v ON v.module_id = m.id
GROUP BY m.id
ORDER BY m.module_path
`

type ListGoproxyModuleSummariesRow struct {
	ModulePath    string      `json:"module_path"`
	Source        string      `json:"source"`
	LastErrorKind string      `json:"last_error_kind"`
	LastError     string      `json:"last_error"`
	LastErrorAt   *time.Time  `json:"last_error_at"`
	LastSuccessAt *time.Time  `json:"last_success_at"`
	VersionCount  int64       `json:"version_count"`
	Bytes         interface{} `json:"bytes"`
	LastFetchedAt interface{} `json:"last_fetched_at"`
}

// One row per cached module for the admin dashboard: how much of it is cached,
// when it last worked, and how it last failed.
func (q *Queries) ListGoproxyModuleSummaries(ctx context.Context) ([]ListGoproxyModuleSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoproxyModuleSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoproxyModuleSummariesRow{}
	for rows.Next() {
		var i ListGoproxyModuleSummariesRow
		if err := rows.Scan(
			&i.ModulePath,
			&i.Source,
			&i.LastErrorKind,
			&i.LastError,
			&i.LastErrorAt,
			&i.LastSuccessAt,
			&i.VersionCount,
			&i.Bytes,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoproxyVersionsByModule = `-- name: ListGoproxyVersionsByModule :many
SELECT v.version, v.commit_sha, v.committed_at, v.zip_storage_key, v.zip_size, v.fetched_at
FROM goproxy_versions v
JOIN goproxy_modules m ON m.id = v.module_id
WHERE m.module_path = ?
ORDER BY v.fetched_at DESC
`

type ListGoproxyVersionsByModuleRow struct {
	Version       string     `json:"version"`
	CommitSha     string     `json:"commit_sha"`
	CommittedAt   *time.Time `json:"committed_at"`
	ZipStorageKey string     `json:"zip_storage_key"`
	ZipSize       int64      `json:"zip_size"`
	FetchedAt     time.Time  `json:"fetched_at"`
}

func (q *Queries) ListGoproxyVersionsByModule(ctx context.Context, modulePath string) ([]ListGoproxyVersionsByModuleRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoproxyVersionsByModule, modulePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoproxyVersionsByModuleRow{}
	for rows.Next() {
		var i ListGoproxyVersionsByModuleRow
		if err := rows.Scan(
			&i.Version,
			&i.CommitSha,
			&i.CommittedAt,
			&i.ZipStorageKey,
			&i.ZipSize,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGoproxyModuleError = `-- name: MarkGoproxyModuleError :exec
UPDATE goproxy_modules
SET last_error_kind = ?, last_error = ?, last_error_at = datetime('now')
WHERE id = ?
`

type MarkGoproxyModuleErrorParams struct {
	LastErrorKind string `json:"last_error_kind"`
	LastError     string `json:"last_error"`
	ID            int64  `json:"id"`
}

func (q *Queries) MarkGoproxyModuleError(ctx context.Context, arg MarkGoproxyModuleErrorParams) error {
	_, err := q.db.ExecContext(ctx, markGoproxyModuleError, arg.LastErrorKind, arg.LastError, arg.ID)
	return err
}

const markGoproxyModuleSuccess = `-- name: MarkGoproxyModuleSuccess :exec
UPDATE goproxy_modules
SET last_success_at = datetime('now'), last_error_kind = '', last_error = '', last_error_at = NULL
WHERE id = ?
`

func (q *Queries) MarkGoproxyModuleSuccess(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markGoproxyModuleSuccess, id)
	return err
}

const setGoproxyVersionZip = `-- name: SetGoproxyVersionZip :exec
UPDATE goproxy_versions SET zip_storage_key = ?, zip_size = ?, fetched_at = datetime('now')
WHERE module_id = ? AND version = ?
`

type SetGoproxyVersionZipParams struct {
	ZipStorageKey string `json:"zip_storage_key"`
	ZipSize       int64  `json:"zip_size"`
	ModuleID      int64  `json:"module_id"`
	Version       string `json:"version"`
}

func (q *Queries) SetGoproxyVersionZip(ctx context.Context, arg SetGoproxyVersionZipParams) error {
	_, err := q.db.ExecContext(ctx, setGoproxyVersionZip,
		arg.ZipStorageKey,
		arg.ZipSize,
		arg.ModuleID,
		arg.Version,
	)
	return err
}

const upsertGoproxyModule = `-- name: UpsertGoproxyModule :one
INSERT INTO goproxy_modules (module_path, source)
VALUES (?, ?)
ON CONFLICT(module_path) DO UPDATE SET source = excluded.source
RETURNING id
`

type UpsertGoproxyModuleParams struct {
	ModulePath string `json:"module_path"`
	Source     string `json:"source"`
}

func (q *Queries) UpsertGoproxyModule(ctx context.Context, arg UpsertGoproxyModuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertGoproxyModule, arg.ModulePath, arg.Source)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertGoproxyVersion = `-- name: UpsertGoproxyVersion :exec
INSERT INTO goproxy_versions (module_id, version, commit_sha, committed_at, go_mod, zip_storage_key, zip_size)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(module_id, version) DO UPDATE SET
    commit_sha      = excluded.commit_sha,
    committed_at    = excluded.committed_at,
    go_mod          = excluded.go_mod,
    zip_storage_key = CASE WHEN excluded.zip_storage_key != '' THEN excluded.zip_storage_key ELSE goproxy_versions.zip_storage_key END,
    zip_size        = CASE WHEN excluded.zip_storage_key != '' THEN excluded.zip_size ELSE goproxy_versions.zip_size END,
    fetched_at      = datetime('now')
`

type UpsertGoproxyVersionParams struct {
	ModuleID      int64      `json:"module_id"`
	Version       string     `json:"version"`
	CommitSha     string     `json:"commit_sha"`
	CommittedAt   *time.Time `json:"committed_at"`
	GoMod         string     `json:"go_mod"`
	ZipStorageKey string     `json:"zip_storage_key"`
	ZipSize       int64      `json:"zip_size"`
}

func (q *Queries) UpsertGoproxyVersion(ctx context.Context, arg UpsertGoproxyVersionParams) error {
	_, err := q.db.ExecContext(ctx, upsertGoproxyVersion,
		arg.ModuleID,
		arg.Version,
		arg.CommitSha,
		arg.CommittedAt,
		arg.GoMod,
		arg.ZipStorageKey,
		arg.ZipSize,
	)
	return err
}
