// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type ApiToken struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	TokenHash   string     `json:"-"`
	TokenPrefix string     `json:"token_prefix"`
	ProjectID   *int64     `json:"project_id"`
	Scopes      string     `json:"scopes"`
	ExpiresAt   *time.Time `json:"expires_at"`
	CreatedAt   time.Time  `json:"created_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
}

type Artifact struct {
	ID                 int64     `json:"id"`
	ReleaseID          int64     `json:"release_id"`
	OS                 OS        `json:"os"`
	Arch               Arch      `json:"arch"`
	Kind               Kind      `json:"kind"`
	StorageKey         string    `json:"storage_key"`
	Size               int64     `json:"size"`
	SHA256             string    `json:"sha256"`
	StrippedStorageKey string    `json:"stripped_storage_key"`
	StrippedSize       int64     `json:"stripped_size"`
	StrippedSHA256     string    `json:"stripped_sha256"`
	DebugStorageKey    string    `json:"debug_storage_key"`
	DebugSize          int64     `json:"debug_size"`
	Filename           string    `json:"filename"`
	CreatedAt          time.Time `json:"created_at"`
}

type DownloadCount struct {
	ArtifactID int64 `json:"artifact_id"`
	Count      int64 `json:"count"`
}

type OciBlobLink struct {
	ID         int64     `json:"id"`
	ProjectID  int64     `json:"project_id"`
	StorageKey string    `json:"storage_key"`
	MediaType  string    `json:"media_type"`
	Size       int64     `json:"size"`
	IsManifest int64     `json:"is_manifest"`
	CreatedAt  time.Time `json:"created_at"`
}

type OciTag struct {
	ID             int64     `json:"id"`
	ProjectID      int64     `json:"project_id"`
	Tag            string    `json:"tag"`
	ManifestDigest string    `json:"manifest_digest"`
	ReleaseID      int64     `json:"release_id"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type OidcPolicy struct {
	ID             int64     `json:"id"`
	Issuer         string    `json:"issuer"`
	SubjectPattern string    `json:"subject_pattern"`
	Audience       string    `json:"audience"`
	ProjectID      *int64    `json:"project_id"`
	Scopes         string    `json:"scopes"`
	CreatedAt      time.Time `json:"created_at"`
}

type PackagedArtifact struct {
	ID         int64     `json:"id"`
	ArtifactID int64     `json:"artifact_id"`
	Format     string    `json:"format"`
	StorageKey string    `json:"storage_key"`
	Size       int64     `json:"size"`
	SHA256     string    `json:"sha256"`
	Filename   string    `json:"filename"`
	Metadata   string    `json:"metadata"`
	CreatedAt  time.Time `json:"created_at"`
}

type Project struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Homepage    string     `json:"homepage"`
	License     string     `json:"license"`
	IsPrivate   bool       `json:"is_private"`
	Versioning  Versioning `json:"versioning"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type Release struct {
	ID          int64      `json:"id"`
	ProjectID   int64      `json:"project_id"`
	Version     string     `json:"version"`
	VersionNum  int64      `json:"version_num"`
	GitBranch   string     `json:"git_branch"`
	GitCommit   string     `json:"git_commit"`
	Notes       string     `json:"notes"`
	OciUser     string     `json:"oci_user"`
	Published   bool       `json:"published"`
	CreatedAt   time.Time  `json:"created_at"`
	PublishedAt *time.Time `json:"published_at"`
}

type Site struct {
	ID         int64     `json:"id"`
	ProjectID  int64     `json:"project_id"`
	Branch     string    `json:"branch"`
	StorageKey string    `json:"storage_key"`
	Size       int64     `json:"size"`
	SHA256     string    `json:"sha256"`
	FileCount  int64     `json:"file_count"`
	GitCommit  string    `json:"git_commit"`
	IsPublic   bool      `json:"is_public"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
