// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: oci.sql

package db

import (
	"context"
)

const getOCIBlobLink = `-- name: GetOCIBlobLink :one
SELECT id, project_id, storage_key, media_type, size, is_manifest, created_at
FROM oci_blob_links WHERE project_id = ? AND storage_key = ?
`

type GetOCIBlobLinkParams struct {
	ProjectID  int64  `json:"project_id"`
	StorageKey string `json:"storage_key"`
}

func (q *Queries) GetOCIBlobLink(ctx context.Context, arg GetOCIBlobLinkParams) (OciBlobLink, error) {
	row := q.db.QueryRowContext(ctx, getOCIBlobLink, arg.ProjectID, arg.StorageKey)
	var i OciBlobLink
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StorageKey,
		&i.MediaType,
		&i.Size,
		&i.IsManifest,
		&i.CreatedAt,
	)
	return i, err
}

const getOCITag = `-- name: GetOCITag :one
SELECT id, project_id, tag, manifest_digest, release_id, updated_at
FROM oci_tags WHERE project_id = ? AND tag = ?
`

type GetOCITagParams struct {
	ProjectID int64  `json:"project_id"`
	Tag       string `json:"tag"`
}

func (q *Queries) GetOCITag(ctx context.Context, arg GetOCITagParams) (OciTag, error) {
	row := q.db.QueryRowContext(ctx, getOCITag, arg.ProjectID, arg.Tag)
	var i OciTag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Tag,
		&i.ManifestDigest,
		&i.ReleaseID,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOCIBlobLink = `-- name: InsertOCIBlobLink :exec
INSERT OR IGNORE INTO oci_blob_links (project_id, storage_key, media_type, size, is_manifest)
VALUES (?, ?, ?, ?, ?)
`

type InsertOCIBlobLinkParams struct {
	ProjectID  int64  `json:"project_id"`
	StorageKey string `json:"storage_key"`
	MediaType  string `json:"media_type"`
	Size       int64  `json:"size"`
	IsManifest int64  `json:"is_manifest"`
}

func (q *Queries) InsertOCIBlobLink(ctx context.Context, arg InsertOCIBlobLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertOCIBlobLink,
		arg.ProjectID,
		arg.StorageKey,
		arg.MediaType,
		arg.Size,
		arg.IsManifest,
	)
	return err
}

const listOCITags = `-- name: ListOCITags :many
SELECT id, project_id, tag, manifest_digest, release_id, updated_at
FROM oci_tags WHERE project_id = ? ORDER BY tag
`

func (q *Queries) ListOCITags(ctx context.Context, projectID int64) ([]OciTag, error) {
	rows, err := q.db.QueryContext(ctx, listOCITags, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OciTag{}
	for rows.Next() {
		var i OciTag
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Tag,
			&i.ManifestDigest,
			&i.ReleaseID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOCITag = `-- name: UpsertOCITag :exec
INSERT INTO oci_tags (project_id, tag, manifest_digest, release_id, updated_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT(project_id, tag) DO UPDATE SET
  manifest_digest = excluded.manifest_digest,
  release_id = excluded.release_id,
  updated_at = datetime('now')
`

type UpsertOCITagParams struct {
	ProjectID      int64  `json:"project_id"`
	Tag            string `json:"tag"`
	ManifestDigest string `json:"manifest_digest"`
	ReleaseID      int64  `json:"release_id"`
}

func (q *Queries) UpsertOCITag(ctx context.Context, arg UpsertOCITagParams) error {
	_, err := q.db.ExecContext(ctx, upsertOCITag,
		arg.ProjectID,
		arg.Tag,
		arg.ManifestDigest,
		arg.ReleaseID,
	)
	return err
}
