// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: oidc.sql

package db

import (
	"context"
	"database/sql"
)

const deleteOIDCPolicyByID = `-- name: DeleteOIDCPolicyByID :execresult
DELETE FROM oidc_policies WHERE id = ?
`

func (q *Queries) DeleteOIDCPolicyByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOIDCPolicyByID, id)
}

const getOIDCPolicyByID = `-- name: GetOIDCPolicyByID :one
SELECT id, issuer, subject_pattern, audience, project_id, scopes, created_at
FROM oidc_policies WHERE id = ?
`

func (q *Queries) GetOIDCPolicyByID(ctx context.Context, id int64) (OidcPolicy, error) {
	row := q.db.QueryRowContext(ctx, getOIDCPolicyByID, id)
	var i OidcPolicy
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.SubjectPattern,
		&i.Audience,
		&i.ProjectID,
		&i.Scopes,
		&i.CreatedAt,
	)
	return i, err
}

const insertOIDCPolicy = `-- name: InsertOIDCPolicy :execresult
INSERT INTO oidc_policies (issuer, subject_pattern, audience, project_id, scopes)
VALUES (?, ?, ?, ?, ?)
`

type InsertOIDCPolicyParams struct {
	Issuer         string `json:"issuer"`
	SubjectPattern string `json:"subject_pattern"`
	Audience       string `json:"audience"`
	ProjectID      *int64 `json:"project_id"`
	Scopes         string `json:"scopes"`
}

func (q *Queries) InsertOIDCPolicy(ctx context.Context, arg InsertOIDCPolicyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertOIDCPolicy,
		arg.Issuer,
		arg.SubjectPattern,
		arg.Audience,
		arg.ProjectID,
		arg.Scopes,
	)
}

const listAllOIDCPolicies = `-- name: ListAllOIDCPolicies :many
SELECT id, issuer, subject_pattern, audience, project_id, scopes, created_at
FROM oidc_policies ORDER BY created_at DESC
`

func (q *Queries) ListAllOIDCPolicies(ctx context.Context) ([]OidcPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listAllOIDCPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcPolicy{}
	for rows.Next() {
		var i OidcPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.SubjectPattern,
			&i.Audience,
			&i.ProjectID,
			&i.Scopes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCPoliciesByIssuer = `-- name: ListOIDCPoliciesByIssuer :many
SELECT id, issuer, subject_pattern, audience, project_id, scopes, created_at
FROM oidc_policies WHERE issuer = ?
`

func (q *Queries) ListOIDCPoliciesByIssuer(ctx context.Context, issuer string) ([]OidcPolicy, error) {
	rows, err := q.db.QueryContext(ctx, listOIDCPoliciesByIssuer, issuer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcPolicy{}
	for rows.Next() {
		var i OidcPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.SubjectPattern,
			&i.Audience,
			&i.ProjectID,
			&i.Scopes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
