// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, description, homepage, license, is_private, versioning, default_branch, created_at, updated_at
FROM projects WHERE name = ?
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Homepage,
		&i.License,
		&i.IsPrivate,
		&i.Versioning,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :execresult
INSERT INTO projects (name, description, homepage, license, is_private, versioning)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertProjectParams struct {
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Homepage    string     `json:"homepage"`
	License     string     `json:"license"`
	IsPrivate   bool       `json:"is_private"`
	Versioning  Versioning `json:"versioning"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertProject,
		arg.Name,
		arg.Description,
		arg.Homepage,
		arg.License,
		arg.IsPrivate,
		arg.Versioning,
	)
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT id, name, description, homepage, license, is_private, versioning, default_branch, created_at, updated_at
FROM projects ORDER BY name
`

func (q *Queries) ListAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Homepage,
			&i.License,
			&i.IsPrivate,
			&i.Versioning,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectDefaultBranch = `-- name: SetProjectDefaultBranch :exec
UPDATE projects SET default_branch = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetProjectDefaultBranchParams struct {
	DefaultBranch string `json:"default_branch"`
	ID            int64  `json:"id"`
}

func (q *Queries) SetProjectDefaultBranch(ctx context.Context, arg SetProjectDefaultBranchParams) error {
	_, err := q.db.ExecContext(ctx, setProjectDefaultBranch, arg.DefaultBranch, arg.ID)
	return err
}

const setProjectVisibility = `-- name: SetProjectVisibility :exec
UPDATE projects SET is_private = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetProjectVisibilityParams struct {
	IsPrivate bool  `json:"is_private"`
	ID        int64 `json:"id"`
}

func (q *Queries) SetProjectVisibility(ctx context.Context, arg SetProjectVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, setProjectVisibility, arg.IsPrivate, arg.ID)
	return err
}
