// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: releases.sql

package db

import (
	"context"
	"database/sql"
)

const getLatestPublishedRelease = `-- name: GetLatestPublishedRelease :one
SELECT id, project_id, version, version_num, git_branch, git_commit, notes, oci_user, published, created_at, published_at
FROM releases WHERE project_id = ? AND published = 1
ORDER BY version_num DESC LIMIT 1
`

func (q *Queries) GetLatestPublishedRelease(ctx context.Context, projectID int64) (Release, error) {
	row := q.db.QueryRowContext(ctx, getLatestPublishedRelease, projectID)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.VersionNum,
		&i.GitBranch,
		&i.GitCommit,
		&i.Notes,
		&i.OciUser,
		&i.Published,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getLatestPublishedReleaseByBranch = `-- name: GetLatestPublishedReleaseByBranch :one
SELECT id, project_id, version, version_num, git_branch, git_commit, notes, oci_user, published, created_at, published_at
FROM releases WHERE project_id = ? AND git_branch = ? AND published = 1
ORDER BY version_num DESC LIMIT 1
`

type GetLatestPublishedReleaseByBranchParams struct {
	ProjectID int64  `json:"project_id"`
	GitBranch string `json:"git_branch"`
}

func (q *Queries) GetLatestPublishedReleaseByBranch(ctx context.Context, arg GetLatestPublishedReleaseByBranchParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, getLatestPublishedReleaseByBranch, arg.ProjectID, arg.GitBranch)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.VersionNum,
		&i.GitBranch,
		&i.GitCommit,
		&i.Notes,
		&i.OciUser,
		&i.Published,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getMaxVersionNum = `-- name: GetMaxVersionNum :one
SELECT CAST(COALESCE(MAX(version_num), 0) AS INTEGER) AS max_version_num FROM releases WHERE project_id = ?
`

func (q *Queries) GetMaxVersionNum(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMaxVersionNum, projectID)
	var max_version_num int64
	err := row.Scan(&max_version_num)
	return max_version_num, err
}

const getReleaseByProjectAndVersion = `-- name: GetReleaseByProjectAndVersion :one
SELECT id, project_id, version, version_num, git_branch, git_commit, notes, oci_user, published, created_at, published_at
FROM releases WHERE project_id = ? AND version = ?
`

type GetReleaseByProjectAndVersionParams struct {
	ProjectID int64  `json:"project_id"`
	Version   string `json:"version"`
}

func (q *Queries) GetReleaseByProjectAndVersion(ctx context.Context, arg GetReleaseByProjectAndVersionParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByProjectAndVersion, arg.ProjectID, arg.Version)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.VersionNum,
		&i.GitBranch,
		&i.GitCommit,
		&i.Notes,
		&i.OciUser,
		&i.Published,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const insertRelease = `-- name: InsertRelease :execresult
INSERT INTO releases (project_id, version, version_num, git_branch, git_commit, notes, oci_user)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertReleaseParams struct {
	ProjectID  int64  `json:"project_id"`
	Version    string `json:"version"`
	VersionNum int64  `json:"version_num"`
	GitBranch  string `json:"git_branch"`
	GitCommit  string `json:"git_commit"`
	Notes      string `json:"notes"`
	OciUser    string `json:"oci_user"`
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertRelease,
		arg.ProjectID,
		arg.Version,
		arg.VersionNum,
		arg.GitBranch,
		arg.GitCommit,
		arg.Notes,
		arg.OciUser,
	)
}

const listReleasesByProject = `-- name: ListReleasesByProject :many
SELECT id, project_id, version, version_num, git_branch, git_commit, notes, oci_user, published, created_at, published_at
FROM releases WHERE project_id = ? ORDER BY version_num DESC
`

func (q *Queries) ListReleasesByProject(ctx context.Context, projectID int64) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listReleasesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Release{}
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.VersionNum,
			&i.GitBranch,
			&i.GitCommit,
			&i.Notes,
			&i.OciUser,
			&i.Published,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishRelease = `-- name: PublishRelease :exec
UPDATE releases SET published = 1, published_at = datetime('now') WHERE id = ?
`

func (q *Queries) PublishRelease(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, publishRelease, id)
	return err
}
