// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: retention.sql

package db

import (
	"context"
	"time"
)

const deleteReleaseArtifacts = `-- name: DeleteReleaseArtifacts :exec
DELETE FROM artifacts WHERE release_id = ?
`

func (q *Queries) DeleteReleaseArtifacts(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseArtifacts, releaseID)
	return err
}

const deleteReleaseDownloadCounts = `-- name: DeleteReleaseDownloadCounts :exec
DELETE FROM download_counts WHERE artifact_id IN (SELECT id FROM artifacts WHERE release_id = ?)
`

func (q *Queries) DeleteReleaseDownloadCounts(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseDownloadCounts, releaseID)
	return err
}

const deleteReleaseOCITags = `-- name: DeleteReleaseOCITags :exec
DELETE FROM oci_tags WHERE release_id = ?
`

func (q *Queries) DeleteReleaseOCITags(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseOCITags, releaseID)
	return err
}

const deleteReleasePackagedArtifacts = `-- name: DeleteReleasePackagedArtifacts :exec
DELETE FROM packaged_artifacts WHERE artifact_id IN (SELECT id FROM artifacts WHERE release_id = ?)
`

func (q *Queries) DeleteReleasePackagedArtifacts(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleasePackagedArtifacts, releaseID)
	return err
}

const deleteReleaseRow = `-- name: DeleteReleaseRow :exec
DELETE FROM releases WHERE id = ?
`

func (q *Queries) DeleteReleaseRow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseRow, id)
	return err
}

const getRetentionSettings = `-- name: GetRetentionSettings :one
SELECT keep_n, recency_hours FROM retention_settings WHERE id = 1
`

type GetRetentionSettingsRow struct {
	KeepN        int64 `json:"keep_n"`
	RecencyHours int64 `json:"recency_hours"`
}

func (q *Queries) GetRetentionSettings(ctx context.Context) (GetRetentionSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getRetentionSettings)
	var i GetRetentionSettingsRow
	err := row.Scan(&i.KeepN, &i.RecencyHours)
	return i, err
}

const isBlobReferenced = `-- name: IsBlobReferenced :one
SELECT EXISTS(
    SELECT 1 FROM artifacts a
      WHERE a.storage_key = ?1 OR a.stripped_storage_key = ?1 OR a.debug_storage_key = ?1
    UNION ALL SELECT 1 FROM packaged_artifacts pa WHERE pa.storage_key = ?1
    UNION ALL SELECT 1 FROM sites s               WHERE s.storage_key = ?1
    UNION ALL SELECT 1 FROM oci_blob_links obl    WHERE obl.storage_key = ?1
    UNION ALL SELECT 1 FROM goproxy_versions gv   WHERE gv.zip_storage_key = ?1
) AS referenced
`

// Global (un-scoped) generalization of BlobBelongsToProject: is this content
// blob referenced by ANY row, in ANY project? Used by the GC sweep to decide
// whether a freed candidate key is safe to delete from storage.
func (q *Queries) IsBlobReferenced(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isBlobReferenced, key)
	var referenced int64
	err := row.Scan(&referenced)
	return referenced, err
}

const listAbandonedReleases = `-- name: ListAbandonedReleases :many
SELECT r.id, r.project_id, p.name AS project_name, r.git_branch, r.version
FROM releases r
JOIN projects p ON p.id = r.project_id
WHERE r.published = 0 AND r.draft = 0 AND r.created_at < datetime(?1)
`

type ListAbandonedReleasesRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	ProjectName string `json:"project_name"`
	GitBranch   string `json:"git_branch"`
	Version     string `json:"version"`
}

// Unpublished (partial/failed upload) releases older than the cutoff.
//
// Drafts are deliberately excluded: an unpublished release used to mean only
// "an upload that never finished", so sweeping them was safe. A draft is an
// unpublished release its owner MEANT to keep (downloadable by exact version,
// invisible to latest/brew/apt/npm/OCI), and deleting one because it got old
// would be deleting the feature.
func (q *Queries) ListAbandonedReleases(ctx context.Context, cutoff interface{}) ([]ListAbandonedReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAbandonedReleases, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAbandonedReleasesRow{}
	for rows.Next() {
		var i ListAbandonedReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.GitBranch,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactFiles = `-- name: ListArtifactFiles :many
SELECT a.id, a.release_id, a.os, a.arch, a.kind, a.filename, a.exe_format,
       a.storage_key, a.size, a.sha256,
       a.stripped_storage_key, a.stripped_size, a.stripped_sha256,
       a.debug_storage_key, a.debug_size,
       a.created_at,
       r.version, r.version_num, r.git_branch, r.published, r.draft,
       r.project_id, p.name AS project_name
FROM artifacts a
JOIN releases r ON r.id = a.release_id
JOIN projects p ON p.id = r.project_id
ORDER BY p.name, r.version_num, a.id
`

type ListArtifactFilesRow struct {
	ID                 int64     `json:"id"`
	ReleaseID          int64     `json:"release_id"`
	OS                 OS        `json:"os"`
	Arch               Arch      `json:"arch"`
	Kind               Kind      `json:"kind"`
	Filename           string    `json:"filename"`
	ExeFormat          string    `json:"exe_format"`
	StorageKey         string    `json:"storage_key"`
	Size               int64     `json:"size"`
	SHA256             string    `json:"sha256"`
	StrippedStorageKey string    `json:"stripped_storage_key"`
	StrippedSize       int64     `json:"stripped_size"`
	StrippedSHA256     string    `json:"stripped_sha256"`
	DebugStorageKey    string    `json:"debug_storage_key"`
	DebugSize          int64     `json:"debug_size"`
	CreatedAt          time.Time `json:"created_at"`
	Version            string    `json:"version"`
	VersionNum         int64     `json:"version_num"`
	GitBranch          string    `json:"git_branch"`
	Published          bool      `json:"published"`
	Draft              bool      `json:"draft"`
	ProjectID          int64     `json:"project_id"`
	ProjectName        string    `json:"project_name"`
}

// Every artifact row with the up to three blobs it references (raw, stripped,
// debug) and the release/project context needed to explain why it is kept.
// Feeds the retention inventory; the caller expands one row into one entry per
// non-empty storage key.
func (q *Queries) ListArtifactFiles(ctx context.Context) ([]ListArtifactFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactFilesRow{}
	for rows.Next() {
		var i ListArtifactFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.OS,
			&i.Arch,
			&i.Kind,
			&i.Filename,
			&i.ExeFormat,
			&i.StorageKey,
			&i.Size,
			&i.SHA256,
			&i.StrippedStorageKey,
			&i.StrippedSize,
			&i.StrippedSHA256,
			&i.DebugStorageKey,
			&i.DebugSize,
			&i.CreatedAt,
			&i.Version,
			&i.VersionNum,
			&i.GitBranch,
			&i.Published,
			&i.Draft,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvictableReleases = `-- name: ListEvictableReleases :many
SELECT r.id, r.project_id, p.name AS project_name, r.git_branch, r.version, r.version_num
FROM releases r
JOIN projects p ON p.id = r.project_id
WHERE r.published = 1
  AND r.created_at < datetime(?1)
  AND r.id NOT IN (SELECT release_id FROM oci_tags)
  AND r.id NOT IN (SELECT release_id FROM artifacts WHERE kind = 'docker')
  AND (
      SELECT COUNT(*) FROM releases r2
      WHERE r2.project_id = r.project_id
        AND r2.git_branch = r.git_branch
        AND r2.published = 1
        AND r2.version_num > r.version_num
  ) >= max(?2, 1)
ORDER BY r.project_id, r.git_branch, r.version_num DESC
`

type ListEvictableReleasesParams struct {
	RecencyCutoff interface{} `json:"recency_cutoff"`
	KeepN         interface{} `json:"keep_n"`
}

type ListEvictableReleasesRow struct {
	ID          int64  `json:"id"`
	ProjectID   int64  `json:"project_id"`
	ProjectName string `json:"project_name"`
	GitBranch   string `json:"git_branch"`
	Version     string `json:"version"`
	VersionNum  int64  `json:"version_num"`
}

// Published releases past keep-N on each (project, git_branch). A release is
// evictable when at least max(keep_n, 1) NEWER published releases exist on the
// same branch. The max(..., 1) floor means the per-branch tip (zero newer) is
// ALWAYS kept, even if keep_n is set to 0 -- so eviction can never remove a
// branch's latest published build (which /dl/.../branch/... resolves). Also
// excludes anything newer than the recency cutoff, tagged releases, and
// pushed-docker releases (their blobs live in project-scoped oci_blob_links, not
// release-cascade-able). Correlated-subquery form (sqlc's SQLite analyzer does
// not support window-fn aliases in WHERE).
func (q *Queries) ListEvictableReleases(ctx context.Context, arg ListEvictableReleasesParams) ([]ListEvictableReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvictableReleases, arg.RecencyCutoff, arg.KeepN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEvictableReleasesRow{}
	for rows.Next() {
		var i ListEvictableReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.GitBranch,
			&i.Version,
			&i.VersionNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoproxyBlobFiles = `-- name: ListGoproxyBlobFiles :many
SELECT gv.id, gm.module_path, gv.version, gv.zip_storage_key, gv.zip_size, gv.fetched_at
FROM goproxy_versions gv
JOIN goproxy_modules gm ON gm.id = gv.module_id
WHERE gv.zip_storage_key != ''
ORDER BY gm.module_path, gv.version
`

type ListGoproxyBlobFilesRow struct {
	ID            int64     `json:"id"`
	ModulePath    string    `json:"module_path"`
	Version       string    `json:"version"`
	ZipStorageKey string    `json:"zip_storage_key"`
	ZipSize       int64     `json:"zip_size"`
	FetchedAt     time.Time `json:"fetched_at"`
}

// Every cached Go module zip. Cached upstream modules are not projects, so
// release eviction never frees them either.
func (q *Queries) ListGoproxyBlobFiles(ctx context.Context) ([]ListGoproxyBlobFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoproxyBlobFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoproxyBlobFilesRow{}
	for rows.Next() {
		var i ListGoproxyBlobFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ModulePath,
			&i.Version,
			&i.ZipStorageKey,
			&i.ZipSize,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOCIBlobFiles = `-- name: ListOCIBlobFiles :many
SELECT obl.id, obl.project_id, p.name AS project_name, obl.storage_key,
       obl.media_type, obl.size, obl.is_manifest, obl.created_at
FROM oci_blob_links obl
JOIN projects p ON p.id = obl.project_id
ORDER BY p.name, obl.id
`

type ListOCIBlobFilesRow struct {
	ID          int64     `json:"id"`
	ProjectID   int64     `json:"project_id"`
	ProjectName string    `json:"project_name"`
	StorageKey  string    `json:"storage_key"`
	MediaType   string    `json:"media_type"`
	Size        int64     `json:"size"`
	IsManifest  int64     `json:"is_manifest"`
	CreatedAt   time.Time `json:"created_at"`
}

// Every project-scoped OCI blob link. These are not release-scoped, so release
// eviction never frees them.
func (q *Queries) ListOCIBlobFiles(ctx context.Context) ([]ListOCIBlobFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOCIBlobFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOCIBlobFilesRow{}
	for rows.Next() {
		var i ListOCIBlobFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.StorageKey,
			&i.MediaType,
			&i.Size,
			&i.IsManifest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagedFiles = `-- name: ListPackagedFiles :many
SELECT pa.id, pa.artifact_id, pa.format, pa.storage_key, pa.size, pa.sha256,
       pa.filename, pa.created_at,
       a.release_id, a.os, a.arch, a.kind,
       r.version, r.version_num, r.git_branch, r.published, r.draft,
       r.project_id, p.name AS project_name
FROM packaged_artifacts pa
JOIN artifacts a ON a.id = pa.artifact_id
JOIN releases r ON r.id = a.release_id
JOIN projects p ON p.id = r.project_id
ORDER BY p.name, r.version_num, pa.id
`

type ListPackagedFilesRow struct {
	ID          int64     `json:"id"`
	ArtifactID  int64     `json:"artifact_id"`
	Format      string    `json:"format"`
	StorageKey  string    `json:"storage_key"`
	Size        int64     `json:"size"`
	SHA256      string    `json:"sha256"`
	Filename    string    `json:"filename"`
	CreatedAt   time.Time `json:"created_at"`
	ReleaseID   int64     `json:"release_id"`
	OS          OS        `json:"os"`
	Arch        Arch      `json:"arch"`
	Kind        Kind      `json:"kind"`
	Version     string    `json:"version"`
	VersionNum  int64     `json:"version_num"`
	GitBranch   string    `json:"git_branch"`
	Published   bool      `json:"published"`
	Draft       bool      `json:"draft"`
	ProjectID   int64     `json:"project_id"`
	ProjectName string    `json:"project_name"`
}

// Every stored repackaged artifact (the OCI layers; other formats stream and
// are never stored) with its artifact, release and project context.
func (q *Queries) ListPackagedFiles(ctx context.Context) ([]ListPackagedFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPackagedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackagedFilesRow{}
	for rows.Next() {
		var i ListPackagedFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Format,
			&i.StorageKey,
			&i.Size,
			&i.SHA256,
			&i.Filename,
			&i.CreatedAt,
			&i.ReleaseID,
			&i.OS,
			&i.Arch,
			&i.Kind,
			&i.Version,
			&i.VersionNum,
			&i.GitBranch,
			&i.Published,
			&i.Draft,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseBlobKeys = `-- name: ListReleaseBlobKeys :many
SELECT a.storage_key AS k, a.size AS sz FROM artifacts a WHERE a.release_id = ?1 AND a.storage_key != ''
UNION
SELECT a.stripped_storage_key, a.stripped_size FROM artifacts a WHERE a.release_id = ?1 AND a.stripped_storage_key != ''
UNION
SELECT a.debug_storage_key, a.debug_size FROM artifacts a WHERE a.release_id = ?1 AND a.debug_storage_key != ''
UNION
SELECT pa.storage_key, pa.size FROM packaged_artifacts pa JOIN artifacts a ON pa.artifact_id = a.id
  WHERE a.release_id = ?1 AND pa.storage_key != ''
`

type ListReleaseBlobKeysRow struct {
	K  string `json:"k"`
	Sz int64  `json:"sz"`
}

// Every (storage key, size) a release's artifacts (raw + stripped + debug) and
// their packaged artifacts reference. Collected BEFORE the cascade delete so the
// sweep can re-check each key for surviving references and attribute freed bytes.
func (q *Queries) ListReleaseBlobKeys(ctx context.Context, releaseID int64) ([]ListReleaseBlobKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseBlobKeys, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseBlobKeysRow{}
	for rows.Next() {
		var i ListReleaseBlobKeysRow
		if err := rows.Scan(&i.K, &i.Sz); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseRetentionFacts = `-- name: ListReleaseRetentionFacts :many
SELECT r.id, r.project_id, p.name AS project_name, r.version, r.version_num,
       r.git_branch, r.published, r.draft, r.created_at,
       (SELECT COUNT(*) FROM releases r2
         WHERE r2.project_id = r.project_id
           AND r2.git_branch = r.git_branch
           AND r2.published = 1
           AND r2.version_num > r.version_num) AS newer_published_on_branch,
       (SELECT COUNT(*) FROM oci_tags t WHERE t.release_id = r.id) AS oci_tag_count,
       (SELECT COUNT(*) FROM artifacts a WHERE a.release_id = r.id AND a.kind = 'docker') AS docker_artifact_count
FROM releases r
JOIN projects p ON p.id = r.project_id
ORDER BY p.name, r.version_num
`

type ListReleaseRetentionFactsRow struct {
	ID                     int64     `json:"id"`
	ProjectID              int64     `json:"project_id"`
	ProjectName            string    `json:"project_name"`
	Version                string    `json:"version"`
	VersionNum             int64     `json:"version_num"`
	GitBranch              string    `json:"git_branch"`
	Published              bool      `json:"published"`
	Draft                  bool      `json:"draft"`
	CreatedAt              time.Time `json:"created_at"`
	NewerPublishedOnBranch int64     `json:"newer_published_on_branch"`
	OciTagCount            int64     `json:"oci_tag_count"`
	DockerArtifactCount    int64     `json:"docker_artifact_count"`
}

// One row per release with the facts the keep-N and abandoned queries decide on:
// how many newer published releases share its branch, whether an OCI tag or a
// docker artifact pins it, and its published/draft state. The inventory turns
// these into a per-file hold reason, so an operator can see WHY a release is
// kept instead of only that it is.
func (q *Queries) ListReleaseRetentionFacts(ctx context.Context) ([]ListReleaseRetentionFactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseRetentionFacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseRetentionFactsRow{}
	for rows.Next() {
		var i ListReleaseRetentionFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ProjectName,
			&i.Version,
			&i.VersionNum,
			&i.GitBranch,
			&i.Published,
			&i.Draft,
			&i.CreatedAt,
			&i.NewerPublishedOnBranch,
			&i.OciTagCount,
			&i.DockerArtifactCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedRetentionSettings = `-- name: SeedRetentionSettings :exec
INSERT OR IGNORE INTO retention_settings (id, keep_n, recency_hours) VALUES (1, ?, ?)
`

type SeedRetentionSettingsParams struct {
	KeepN        int64 `json:"keep_n"`
	RecencyHours int64 `json:"recency_hours"`
}

func (q *Queries) SeedRetentionSettings(ctx context.Context, arg SeedRetentionSettingsParams) error {
	_, err := q.db.ExecContext(ctx, seedRetentionSettings, arg.KeepN, arg.RecencyHours)
	return err
}

const sumReclaimableBytes = `-- name: SumReclaimableBytes :one
WITH evictable AS (
    SELECT r.id FROM releases r
    WHERE r.published = 1
      AND r.created_at < datetime(?1)
      AND r.id NOT IN (SELECT release_id FROM oci_tags)
      AND r.id NOT IN (SELECT release_id FROM artifacts WHERE kind = 'docker')
      AND (
          SELECT COUNT(*) FROM releases r2
          WHERE r2.project_id = r.project_id
            AND r2.git_branch = r.git_branch
            AND r2.published = 1
            AND r2.version_num > r.version_num
      ) >= max(?2, 1)
)
SELECT CAST(
    COALESCE((SELECT SUM(a.size + a.stripped_size + a.debug_size)
              FROM artifacts a WHERE a.release_id IN (SELECT id FROM evictable)), 0)
  + COALESCE((SELECT SUM(pa.size) FROM packaged_artifacts pa
              JOIN artifacts a ON pa.artifact_id = a.id
              WHERE a.release_id IN (SELECT id FROM evictable)), 0)
AS INTEGER) AS reclaimable_bytes
`

type SumReclaimableBytesParams struct {
	RecencyCutoff interface{} `json:"recency_cutoff"`
	KeepN         interface{} `json:"keep_n"`
}

// UPPER BOUND on bytes keep-N would free: the logical sizes of evictable releases'
// artifacts (raw+stripped+debug) plus their packaged artifacts. Does not subtract
// blobs still shared with surviving releases, so it overestimates; the gc CLI and
// sweeper report the exact post-refcount figure.
func (q *Queries) SumReclaimableBytes(ctx context.Context, arg SumReclaimableBytesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumReclaimableBytes, arg.RecencyCutoff, arg.KeepN)
	var reclaimable_bytes int64
	err := row.Scan(&reclaimable_bytes)
	return reclaimable_bytes, err
}

const updateRetentionSettings = `-- name: UpdateRetentionSettings :exec
INSERT INTO retention_settings (id, keep_n, recency_hours, updated_at)
VALUES (1, ?, ?, datetime('now'))
ON CONFLICT(id) DO UPDATE SET
    keep_n = excluded.keep_n,
    recency_hours = excluded.recency_hours,
    updated_at = datetime('now')
`

type UpdateRetentionSettingsParams struct {
	KeepN        int64 `json:"keep_n"`
	RecencyHours int64 `json:"recency_hours"`
}

func (q *Queries) UpdateRetentionSettings(ctx context.Context, arg UpdateRetentionSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateRetentionSettings, arg.KeepN, arg.RecencyHours)
	return err
}
