// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: retention.sql

package db

import (
	"context"
)

const deleteReleaseArtifacts = `-- name: DeleteReleaseArtifacts :exec
DELETE FROM artifacts WHERE release_id = ?
`

func (q *Queries) DeleteReleaseArtifacts(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseArtifacts, releaseID)
	return err
}

const deleteReleaseDownloadCounts = `-- name: DeleteReleaseDownloadCounts :exec
DELETE FROM download_counts WHERE artifact_id IN (SELECT id FROM artifacts WHERE release_id = ?)
`

func (q *Queries) DeleteReleaseDownloadCounts(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseDownloadCounts, releaseID)
	return err
}

const deleteReleaseOCITags = `-- name: DeleteReleaseOCITags :exec
DELETE FROM oci_tags WHERE release_id = ?
`

func (q *Queries) DeleteReleaseOCITags(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseOCITags, releaseID)
	return err
}

const deleteReleasePackagedArtifacts = `-- name: DeleteReleasePackagedArtifacts :exec
DELETE FROM packaged_artifacts WHERE artifact_id IN (SELECT id FROM artifacts WHERE release_id = ?)
`

func (q *Queries) DeleteReleasePackagedArtifacts(ctx context.Context, releaseID int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleasePackagedArtifacts, releaseID)
	return err
}

const deleteReleaseRow = `-- name: DeleteReleaseRow :exec
DELETE FROM releases WHERE id = ?
`

func (q *Queries) DeleteReleaseRow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseRow, id)
	return err
}

const isBlobReferenced = `-- name: IsBlobReferenced :one
SELECT EXISTS(
    SELECT 1 FROM artifacts a
      WHERE a.storage_key = ?1 OR a.stripped_storage_key = ?1 OR a.debug_storage_key = ?1
    UNION ALL SELECT 1 FROM packaged_artifacts pa WHERE pa.storage_key = ?1
    UNION ALL SELECT 1 FROM sites s               WHERE s.storage_key = ?1
    UNION ALL SELECT 1 FROM oci_blob_links obl    WHERE obl.storage_key = ?1
) AS referenced
`

// Global (un-scoped) generalization of BlobBelongsToProject: is this content
// blob referenced by ANY row, in ANY project? Used by the GC sweep to decide
// whether a freed candidate key is safe to delete from storage.
func (q *Queries) IsBlobReferenced(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRowContext(ctx, isBlobReferenced, key)
	var referenced int64
	err := row.Scan(&referenced)
	return referenced, err
}

const listAbandonedReleases = `-- name: ListAbandonedReleases :many
SELECT r.id, r.project_id, r.git_branch, r.version
FROM releases r
WHERE r.published = 0 AND r.created_at < datetime(?1)
`

type ListAbandonedReleasesRow struct {
	ID        int64  `json:"id"`
	ProjectID int64  `json:"project_id"`
	GitBranch string `json:"git_branch"`
	Version   string `json:"version"`
}

// Unpublished (partial/failed upload) releases older than the cutoff.
func (q *Queries) ListAbandonedReleases(ctx context.Context, cutoff interface{}) ([]ListAbandonedReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAbandonedReleases, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAbandonedReleasesRow{}
	for rows.Next() {
		var i ListAbandonedReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.GitBranch,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvictableReleases = `-- name: ListEvictableReleases :many
SELECT r.id, r.project_id, r.git_branch, r.version, r.version_num
FROM releases r
WHERE r.published = 1
  AND r.created_at < datetime(?1)
  AND r.id NOT IN (SELECT release_id FROM oci_tags)
  AND r.id NOT IN (SELECT release_id FROM artifacts WHERE kind = 'docker')
  AND (
      SELECT COUNT(*) FROM releases r2
      WHERE r2.project_id = r.project_id
        AND r2.git_branch = r.git_branch
        AND r2.published = 1
        AND r2.version_num > r.version_num
  ) >= max(?2, 1)
ORDER BY r.project_id, r.git_branch, r.version_num DESC
`

type ListEvictableReleasesParams struct {
	RecencyCutoff interface{} `json:"recency_cutoff"`
	KeepN         interface{} `json:"keep_n"`
}

type ListEvictableReleasesRow struct {
	ID         int64  `json:"id"`
	ProjectID  int64  `json:"project_id"`
	GitBranch  string `json:"git_branch"`
	Version    string `json:"version"`
	VersionNum int64  `json:"version_num"`
}

// Published releases past keep-N on each (project, git_branch). A release is
// evictable when at least max(keep_n, 1) NEWER published releases exist on the
// same branch. The max(..., 1) floor means the per-branch tip (zero newer) is
// ALWAYS kept, even if keep_n is set to 0 -- so eviction can never remove a
// branch's latest published build (which /dl/.../branch/... resolves). Also
// excludes anything newer than the recency cutoff, tagged releases, and
// pushed-docker releases (their blobs live in project-scoped oci_blob_links, not
// release-cascade-able). Correlated-subquery form (sqlc's SQLite analyzer does
// not support window-fn aliases in WHERE).
func (q *Queries) ListEvictableReleases(ctx context.Context, arg ListEvictableReleasesParams) ([]ListEvictableReleasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvictableReleases, arg.RecencyCutoff, arg.KeepN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEvictableReleasesRow{}
	for rows.Next() {
		var i ListEvictableReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.GitBranch,
			&i.Version,
			&i.VersionNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseBlobKeys = `-- name: ListReleaseBlobKeys :many
SELECT a.storage_key AS k, a.size AS sz FROM artifacts a WHERE a.release_id = ?1 AND a.storage_key != ''
UNION
SELECT a.stripped_storage_key, a.stripped_size FROM artifacts a WHERE a.release_id = ?1 AND a.stripped_storage_key != ''
UNION
SELECT a.debug_storage_key, a.debug_size FROM artifacts a WHERE a.release_id = ?1 AND a.debug_storage_key != ''
UNION
SELECT pa.storage_key, pa.size FROM packaged_artifacts pa JOIN artifacts a ON pa.artifact_id = a.id
  WHERE a.release_id = ?1 AND pa.storage_key != ''
`

type ListReleaseBlobKeysRow struct {
	K  string `json:"k"`
	Sz int64  `json:"sz"`
}

// Every (storage key, size) a release's artifacts (raw + stripped + debug) and
// their packaged artifacts reference. Collected BEFORE the cascade delete so the
// sweep can re-check each key for surviving references and attribute freed bytes.
func (q *Queries) ListReleaseBlobKeys(ctx context.Context, releaseID int64) ([]ListReleaseBlobKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseBlobKeys, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReleaseBlobKeysRow{}
	for rows.Next() {
		var i ListReleaseBlobKeysRow
		if err := rows.Scan(&i.K, &i.Sz); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumReclaimableBytes = `-- name: SumReclaimableBytes :one
WITH evictable AS (
    SELECT r.id FROM releases r
    WHERE r.published = 1
      AND r.created_at < datetime(?1)
      AND r.id NOT IN (SELECT release_id FROM oci_tags)
      AND r.id NOT IN (SELECT release_id FROM artifacts WHERE kind = 'docker')
      AND (
          SELECT COUNT(*) FROM releases r2
          WHERE r2.project_id = r.project_id
            AND r2.git_branch = r.git_branch
            AND r2.published = 1
            AND r2.version_num > r.version_num
      ) >= max(?2, 1)
)
SELECT CAST(
    COALESCE((SELECT SUM(a.size + a.stripped_size + a.debug_size)
              FROM artifacts a WHERE a.release_id IN (SELECT id FROM evictable)), 0)
  + COALESCE((SELECT SUM(pa.size) FROM packaged_artifacts pa
              JOIN artifacts a ON pa.artifact_id = a.id
              WHERE a.release_id IN (SELECT id FROM evictable)), 0)
AS INTEGER) AS reclaimable_bytes
`

type SumReclaimableBytesParams struct {
	RecencyCutoff interface{} `json:"recency_cutoff"`
	KeepN         interface{} `json:"keep_n"`
}

// UPPER BOUND on bytes keep-N would free: the logical sizes of evictable releases'
// artifacts (raw+stripped+debug) plus their packaged artifacts. Does not subtract
// blobs still shared with surviving releases, so it overestimates; the gc CLI and
// sweeper report the exact post-refcount figure.
func (q *Queries) SumReclaimableBytes(ctx context.Context, arg SumReclaimableBytesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumReclaimableBytes, arg.RecencyCutoff, arg.KeepN)
	var reclaimable_bytes int64
	err := row.Scan(&reclaimable_bytes)
	return reclaimable_bytes, err
}
