// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: run_locks.sql

package db

import (
	"context"
)

const deleteRunLocksBefore = `-- name: DeleteRunLocksBefore :execrows
DELETE FROM run_locks WHERE created_at < datetime(?1)
`

func (q *Queries) DeleteRunLocksBefore(ctx context.Context, cutoff interface{}) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunLocksBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRunLock = `-- name: GetRunLock :one
SELECT value FROM run_locks
WHERE repo_id = ? AND run_id = ? AND run_attempt = ? AND name = ?
`

type GetRunLockParams struct {
	RepoID     string `json:"repo_id"`
	RunID      string `json:"run_id"`
	RunAttempt string `json:"run_attempt"`
	Name       string `json:"name"`
}

func (q *Queries) GetRunLock(ctx context.Context, arg GetRunLockParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getRunLock,
		arg.RepoID,
		arg.RunID,
		arg.RunAttempt,
		arg.Name,
	)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertRunLock = `-- name: InsertRunLock :execrows
INSERT INTO run_locks (repo_id, run_id, run_attempt, name, value)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (repo_id, run_id, run_attempt, name) DO NOTHING
`

type InsertRunLockParams struct {
	RepoID     string `json:"repo_id"`
	RunID      string `json:"run_id"`
	RunAttempt string `json:"run_attempt"`
	Name       string `json:"name"`
	Value      string `json:"value"`
}

func (q *Queries) InsertRunLock(ctx context.Context, arg InsertRunLockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertRunLock,
		arg.RepoID,
		arg.RunID,
		arg.RunAttempt,
		arg.Name,
		arg.Value,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
