// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sites.sql

package db

import (
	"context"
	"database/sql"
)

const deleteSiteByProjectAndBranch = `-- name: DeleteSiteByProjectAndBranch :exec
DELETE FROM sites WHERE project_id = ? AND branch = ?
`

type DeleteSiteByProjectAndBranchParams struct {
	ProjectID int64  `json:"project_id"`
	Branch    string `json:"branch"`
}

func (q *Queries) DeleteSiteByProjectAndBranch(ctx context.Context, arg DeleteSiteByProjectAndBranchParams) error {
	_, err := q.db.ExecContext(ctx, deleteSiteByProjectAndBranch, arg.ProjectID, arg.Branch)
	return err
}

const getSiteByProjectAndBranch = `-- name: GetSiteByProjectAndBranch :one
SELECT id, project_id, branch, storage_key, size, sha256, file_count, git_commit, is_public, created_at, updated_at
FROM sites WHERE project_id = ? AND branch = ?
`

type GetSiteByProjectAndBranchParams struct {
	ProjectID int64  `json:"project_id"`
	Branch    string `json:"branch"`
}

func (q *Queries) GetSiteByProjectAndBranch(ctx context.Context, arg GetSiteByProjectAndBranchParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteByProjectAndBranch, arg.ProjectID, arg.Branch)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Branch,
		&i.StorageKey,
		&i.Size,
		&i.SHA256,
		&i.FileCount,
		&i.GitCommit,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteStorageKey = `-- name: GetSiteStorageKey :one
SELECT storage_key FROM sites WHERE project_id = ? AND branch = ?
`

type GetSiteStorageKeyParams struct {
	ProjectID int64  `json:"project_id"`
	Branch    string `json:"branch"`
}

func (q *Queries) GetSiteStorageKey(ctx context.Context, arg GetSiteStorageKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSiteStorageKey, arg.ProjectID, arg.Branch)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const listSitesByProject = `-- name: ListSitesByProject :many
SELECT id, project_id, branch, storage_key, size, sha256, file_count, git_commit, is_public, created_at, updated_at
FROM sites WHERE project_id = ? ORDER BY updated_at DESC
`

func (q *Queries) ListSitesByProject(ctx context.Context, projectID int64) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listSitesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Branch,
			&i.StorageKey,
			&i.Size,
			&i.SHA256,
			&i.FileCount,
			&i.GitCommit,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSite = `-- name: UpsertSite :execresult
INSERT INTO sites (project_id, branch, storage_key, size, sha256, file_count, git_commit, is_public, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(project_id, branch) DO UPDATE SET
  storage_key = excluded.storage_key,
  size = excluded.size,
  sha256 = excluded.sha256,
  file_count = excluded.file_count,
  git_commit = excluded.git_commit,
  is_public = excluded.is_public,
  updated_at = datetime('now')
`

type UpsertSiteParams struct {
	ProjectID  int64  `json:"project_id"`
	Branch     string `json:"branch"`
	StorageKey string `json:"storage_key"`
	Size       int64  `json:"size"`
	SHA256     string `json:"sha256"`
	FileCount  int64  `json:"file_count"`
	GitCommit  string `json:"git_commit"`
	IsPublic   bool   `json:"is_public"`
}

func (q *Queries) UpsertSite(ctx context.Context, arg UpsertSiteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertSite,
		arg.ProjectID,
		arg.Branch,
		arg.StorageKey,
		arg.Size,
		arg.SHA256,
		arg.FileCount,
		arg.GitCommit,
		arg.IsPublic,
	)
}
