// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteTokenByID = `-- name: DeleteTokenByID :execresult
DELETE FROM api_tokens WHERE id = ?
`

func (q *Queries) DeleteTokenByID(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTokenByID, id)
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, name, token_hash, token_prefix, project_id, scopes, expires_at, created_at, last_used_at
FROM api_tokens WHERE token_hash = ?
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ProjectID,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertToken = `-- name: InsertToken :execresult
INSERT INTO api_tokens (name, token_hash, token_prefix, project_id, scopes)
VALUES (?, ?, ?, ?, ?)
`

type InsertTokenParams struct {
	Name        string `json:"name"`
	TokenHash   string `json:"-"`
	TokenPrefix string `json:"token_prefix"`
	ProjectID   *int64 `json:"project_id"`
	Scopes      string `json:"scopes"`
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertToken,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ProjectID,
		arg.Scopes,
	)
}

const listAllTokens = `-- name: ListAllTokens :many
SELECT id, name, token_prefix, project_id, scopes, expires_at, created_at, last_used_at
FROM api_tokens ORDER BY created_at DESC
`

type ListAllTokensRow struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	TokenPrefix string     `json:"token_prefix"`
	ProjectID   *int64     `json:"project_id"`
	Scopes      string     `json:"scopes"`
	ExpiresAt   *time.Time `json:"expires_at"`
	CreatedAt   time.Time  `json:"created_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
}

func (q *Queries) ListAllTokens(ctx context.Context) ([]ListAllTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTokensRow{}
	for rows.Next() {
		var i ListAllTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.ProjectID,
			&i.Scopes,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = datetime('now') WHERE id = ?
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateTokenLastUsed, id)
	return err
}
